// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kamksqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getActiveInjuriesByUserStmt, err = db.PrepareContext(ctx, getActiveInjuriesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveInjuriesByUser: %w", err)
	}
	if q.getMaxInjuryIDForUserStmt, err = db.PrepareContext(ctx, getMaxInjuryIDForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxInjuryIDForUser: %w", err)
	}
	if q.getQuestionnairesByUserV2Stmt, err = db.PrepareContext(ctx, getQuestionnairesByUserV2); err != nil {
		return nil, fmt.Errorf("error preparing query GetQuestionnairesByUserV2: %w", err)
	}
	if q.insertInjuryStmt, err = db.PrepareContext(ctx, insertInjury); err != nil {
		return nil, fmt.Errorf("error preparing query InsertInjury: %w", err)
	}
	if q.insertQuestionnaireV2Stmt, err = db.PrepareContext(ctx, insertQuestionnaireV2); err != nil {
		return nil, fmt.Errorf("error preparing query InsertQuestionnaireV2: %w", err)
	}
	if q.isQuizDoneTodayV2Stmt, err = db.PrepareContext(ctx, isQuizDoneTodayV2); err != nil {
		return nil, fmt.Errorf("error preparing query IsQuizDoneTodayV2: %w", err)
	}
	if q.markInjuryRecoveredByIDStmt, err = db.PrepareContext(ctx, markInjuryRecoveredByID); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInjuryRecoveredByID: %w", err)
	}
	if q.updateQuestionnaireByTimestampV2Stmt, err = db.PrepareContext(ctx, updateQuestionnaireByTimestampV2); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateQuestionnaireByTimestampV2: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getActiveInjuriesByUserStmt != nil {
		if cerr := q.getActiveInjuriesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveInjuriesByUserStmt: %w", cerr)
		}
	}
	if q.getMaxInjuryIDForUserStmt != nil {
		if cerr := q.getMaxInjuryIDForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxInjuryIDForUserStmt: %w", cerr)
		}
	}
	if q.getQuestionnairesByUserV2Stmt != nil {
		if cerr := q.getQuestionnairesByUserV2Stmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQuestionnairesByUserV2Stmt: %w", cerr)
		}
	}
	if q.insertInjuryStmt != nil {
		if cerr := q.insertInjuryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertInjuryStmt: %w", cerr)
		}
	}
	if q.insertQuestionnaireV2Stmt != nil {
		if cerr := q.insertQuestionnaireV2Stmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertQuestionnaireV2Stmt: %w", cerr)
		}
	}
	if q.isQuizDoneTodayV2Stmt != nil {
		if cerr := q.isQuizDoneTodayV2Stmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isQuizDoneTodayV2Stmt: %w", cerr)
		}
	}
	if q.markInjuryRecoveredByIDStmt != nil {
		if cerr := q.markInjuryRecoveredByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInjuryRecoveredByIDStmt: %w", cerr)
		}
	}
	if q.updateQuestionnaireByTimestampV2Stmt != nil {
		if cerr := q.updateQuestionnaireByTimestampV2Stmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateQuestionnaireByTimestampV2Stmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	getActiveInjuriesByUserStmt          *sql.Stmt
	getMaxInjuryIDForUserStmt            *sql.Stmt
	getQuestionnairesByUserV2Stmt        *sql.Stmt
	insertInjuryStmt                     *sql.Stmt
	insertQuestionnaireV2Stmt            *sql.Stmt
	isQuizDoneTodayV2Stmt                *sql.Stmt
	markInjuryRecoveredByIDStmt          *sql.Stmt
	updateQuestionnaireByTimestampV2Stmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		getActiveInjuriesByUserStmt:          q.getActiveInjuriesByUserStmt,
		getMaxInjuryIDForUserStmt:            q.getMaxInjuryIDForUserStmt,
		getQuestionnairesByUserV2Stmt:        q.getQuestionnairesByUserV2Stmt,
		insertInjuryStmt:                     q.insertInjuryStmt,
		insertQuestionnaireV2Stmt:            q.insertQuestionnaireV2Stmt,
		isQuizDoneTodayV2Stmt:                q.isQuizDoneTodayV2Stmt,
		markInjuryRecoveredByIDStmt:          q.markInjuryRecoveredByIDStmt,
		updateQuestionnaireByTimestampV2Stmt: q.updateQuestionnaireByTimestampV2Stmt,
	}
}
