// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kamksqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteInjuryByIDStmt, err = db.PrepareContext(ctx, deleteInjuryByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInjuryByID: %w", err)
	}
	if q.deleteQuestionnaireByTimestampStmt, err = db.PrepareContext(ctx, deleteQuestionnaireByTimestamp); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteQuestionnaireByTimestamp: %w", err)
	}
	if q.getActiveInjuriesByUserStmt, err = db.PrepareContext(ctx, getActiveInjuriesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveInjuriesByUser: %w", err)
	}
	if q.getMaxInjuryIDForUserStmt, err = db.PrepareContext(ctx, getMaxInjuryIDForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxInjuryIDForUser: %w", err)
	}
	if q.getQuestionnairesByUserStmt, err = db.PrepareContext(ctx, getQuestionnairesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetQuestionnairesByUser: %w", err)
	}
	if q.insertInjuryStmt, err = db.PrepareContext(ctx, insertInjury); err != nil {
		return nil, fmt.Errorf("error preparing query InsertInjury: %w", err)
	}
	if q.insertQuestionnaireStmt, err = db.PrepareContext(ctx, insertQuestionnaire); err != nil {
		return nil, fmt.Errorf("error preparing query InsertQuestionnaire: %w", err)
	}
	if q.isQuizDoneTodayStmt, err = db.PrepareContext(ctx, isQuizDoneToday); err != nil {
		return nil, fmt.Errorf("error preparing query IsQuizDoneToday: %w", err)
	}
	if q.markInjuryRecoveredByIDStmt, err = db.PrepareContext(ctx, markInjuryRecoveredByID); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInjuryRecoveredByID: %w", err)
	}
	if q.updateQuestionnaireByTimestampStmt, err = db.PrepareContext(ctx, updateQuestionnaireByTimestamp); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateQuestionnaireByTimestamp: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteInjuryByIDStmt != nil {
		if cerr := q.deleteInjuryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInjuryByIDStmt: %w", cerr)
		}
	}
	if q.deleteQuestionnaireByTimestampStmt != nil {
		if cerr := q.deleteQuestionnaireByTimestampStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteQuestionnaireByTimestampStmt: %w", cerr)
		}
	}
	if q.getActiveInjuriesByUserStmt != nil {
		if cerr := q.getActiveInjuriesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveInjuriesByUserStmt: %w", cerr)
		}
	}
	if q.getMaxInjuryIDForUserStmt != nil {
		if cerr := q.getMaxInjuryIDForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxInjuryIDForUserStmt: %w", cerr)
		}
	}
	if q.getQuestionnairesByUserStmt != nil {
		if cerr := q.getQuestionnairesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQuestionnairesByUserStmt: %w", cerr)
		}
	}
	if q.insertInjuryStmt != nil {
		if cerr := q.insertInjuryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertInjuryStmt: %w", cerr)
		}
	}
	if q.insertQuestionnaireStmt != nil {
		if cerr := q.insertQuestionnaireStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertQuestionnaireStmt: %w", cerr)
		}
	}
	if q.isQuizDoneTodayStmt != nil {
		if cerr := q.isQuizDoneTodayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isQuizDoneTodayStmt: %w", cerr)
		}
	}
	if q.markInjuryRecoveredByIDStmt != nil {
		if cerr := q.markInjuryRecoveredByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInjuryRecoveredByIDStmt: %w", cerr)
		}
	}
	if q.updateQuestionnaireByTimestampStmt != nil {
		if cerr := q.updateQuestionnaireByTimestampStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateQuestionnaireByTimestampStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	deleteInjuryByIDStmt               *sql.Stmt
	deleteQuestionnaireByTimestampStmt *sql.Stmt
	getActiveInjuriesByUserStmt        *sql.Stmt
	getMaxInjuryIDForUserStmt          *sql.Stmt
	getQuestionnairesByUserStmt        *sql.Stmt
	insertInjuryStmt                   *sql.Stmt
	insertQuestionnaireStmt            *sql.Stmt
	isQuizDoneTodayStmt                *sql.Stmt
	markInjuryRecoveredByIDStmt        *sql.Stmt
	updateQuestionnaireByTimestampStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		deleteInjuryByIDStmt:               q.deleteInjuryByIDStmt,
		deleteQuestionnaireByTimestampStmt: q.deleteQuestionnaireByTimestampStmt,
		getActiveInjuriesByUserStmt:        q.getActiveInjuriesByUserStmt,
		getMaxInjuryIDForUserStmt:          q.getMaxInjuryIDForUserStmt,
		getQuestionnairesByUserStmt:        q.getQuestionnairesByUserStmt,
		insertInjuryStmt:                   q.insertInjuryStmt,
		insertQuestionnaireStmt:            q.insertQuestionnaireStmt,
		isQuizDoneTodayStmt:                q.isQuizDoneTodayStmt,
		markInjuryRecoveredByIDStmt:        q.markInjuryRecoveredByIDStmt,
		updateQuestionnaireByTimestampStmt: q.updateQuestionnaireByTimestampStmt,
	}
}
