// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kamksqlc

import (
	"database/sql"
	"time"
)

type Injury struct {
	UserID      int32
	InjuryType  int32
	Severity    int32
	PainLevel   int32
	Description string
	DateStart   time.Time
	Status      int32
	DateEnd     sql.NullTime
	InjuryID    int32
	Meta        string
}

type Query struct {
	UserID    int32
	QueryType int32
	Answers   string
	Comment   string
	Timestamp time.Time
	Meta      string
	ID        int64
}

type User struct {
	Username          sql.NullInt32
	RoleID            sql.NullInt32
	Password          sql.NullString
	Email             sql.NullString
	SharePermission   sql.NullInt32
	CollectPermission sql.NullInt32
	EulaAccepted      sql.NullInt32
	CreateTime        sql.NullTime
	Message           sql.NullString
	Salt              sql.NullString
}
