// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package kamksqlc

import (
	"database/sql"
)

type Injury struct {
	CompetitorID sql.NullInt32
	InjuryType   sql.NullInt32
	Severity     sql.NullInt32
	PainLevel    sql.NullInt32
	Description  sql.NullString
	DateStart    sql.NullTime
	Status       sql.NullInt32
	DateEnd      sql.NullTime
	InjuryID     sql.NullInt32
	Meta         sql.NullString
}

type Query struct {
	CompetitorID sql.NullInt32
	QueryType    sql.NullInt32
	QuestionID   sql.NullInt32
	Value        sql.NullInt32
	Date         sql.NullTime
	Comment      sql.NullString
	Meta         sql.NullString
}

type QuerysV2 struct {
	CompetitorID sql.NullInt32
	QueryType    sql.NullInt32
	Answers      sql.NullString
	Comment      sql.NullString
	Timestamp    sql.NullTime
	Meta         sql.NullString
}

type User struct {
	Username          sql.NullInt32
	RoleID            sql.NullInt32
	Password          sql.NullString
	Email             sql.NullString
	SharePermission   sql.NullInt32
	CollectPermission sql.NullInt32
	EulaAccepted      sql.NullInt32
	CreateTime        sql.NullTime
	Message           sql.NullString
	Salt              sql.NullString
}
