// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package kamksqlc

import (
	"context"
	"time"
)

const deleteInjuryByID = `-- name: DeleteInjuryByID :execrows
DELETE FROM public.injuries
WHERE user_id = $1
  AND injury_id     = $2
`

type DeleteInjuryByIDParams struct {
	UserID   int32
	InjuryID int32
}

func (q *Queries) DeleteInjuryByID(ctx context.Context, arg DeleteInjuryByIDParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteInjuryByIDStmt, deleteInjuryByID, arg.UserID, arg.InjuryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteQuestionnaireByID = `-- name: DeleteQuestionnaireByID :execrows
DELETE FROM public.querys
WHERE user_id = $1
  AND id           = $2
`

type DeleteQuestionnaireByIDParams struct {
	UserID int32
	ID     int64
}

func (q *Queries) DeleteQuestionnaireByID(ctx context.Context, arg DeleteQuestionnaireByIDParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteQuestionnaireByIDStmt, deleteQuestionnaireByID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveInjuriesByUser = `-- name: GetActiveInjuriesByUser :many
SELECT
  user_id,
  injury_type,
  severity,
  pain_level,
  description,
  date_start,
  status,
  date_end,
  injury_id,
  meta
FROM public.injuries
WHERE user_id = $1
  AND status = 0
ORDER BY date_start DESC
`

func (q *Queries) GetActiveInjuriesByUser(ctx context.Context, userID int32) ([]Injury, error) {
	rows, err := q.query(ctx, q.getActiveInjuriesByUserStmt, getActiveInjuriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Injury
	for rows.Next() {
		var i Injury
		if err := rows.Scan(
			&i.UserID,
			&i.InjuryType,
			&i.Severity,
			&i.PainLevel,
			&i.Description,
			&i.DateStart,
			&i.Status,
			&i.DateEnd,
			&i.InjuryID,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxInjuryIDForUser = `-- name: GetMaxInjuryIDForUser :one
SELECT COALESCE(MAX(injury_id), 0)::int4 AS id
FROM public.injuries
WHERE user_id = $1
`

func (q *Queries) GetMaxInjuryIDForUser(ctx context.Context, userID int32) (int32, error) {
	row := q.queryRow(ctx, q.getMaxInjuryIDForUserStmt, getMaxInjuryIDForUser, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getQuestionnairesByUser = `-- name: GetQuestionnairesByUser :many
SELECT
  id,
  user_id,
  query_type,
  answers,
  comment,
  "timestamp",
  meta
FROM public.querys
WHERE user_id = $1
ORDER BY "timestamp" DESC
`

type GetQuestionnairesByUserRow struct {
	ID        int64
	UserID    int32
	QueryType int32
	Answers   string
	Comment   string
	Timestamp time.Time
	Meta      string
}

func (q *Queries) GetQuestionnairesByUser(ctx context.Context, userID int32) ([]GetQuestionnairesByUserRow, error) {
	rows, err := q.query(ctx, q.getQuestionnairesByUserStmt, getQuestionnairesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionnairesByUserRow
	for rows.Next() {
		var i GetQuestionnairesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QueryType,
			&i.Answers,
			&i.Comment,
			&i.Timestamp,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInjury = `-- name: InsertInjury :exec
INSERT INTO public.injuries (
  user_id, injury_type, severity, pain_level, description, date_start, status, injury_id, meta
) VALUES (
  $1, $2, $3, $4, $5, NOW(), 0, $6, $7
)
`

type InsertInjuryParams struct {
	UserID      int32
	InjuryType  int32
	Severity    int32
	PainLevel   int32
	Description string
	InjuryID    int32
	Meta        string
}

func (q *Queries) InsertInjury(ctx context.Context, arg InsertInjuryParams) error {
	_, err := q.exec(ctx, q.insertInjuryStmt, insertInjury,
		arg.UserID,
		arg.InjuryType,
		arg.Severity,
		arg.PainLevel,
		arg.Description,
		arg.InjuryID,
		arg.Meta,
	)
	return err
}

const insertQuestionnaire = `-- name: InsertQuestionnaire :one
INSERT INTO public.querys (
  user_id, query_type, answers, comment, "timestamp", meta
) VALUES (
  $1, $2, $3, $4, NOW(), $5
)
RETURNING id
`

type InsertQuestionnaireParams struct {
	UserID    int32
	QueryType int32
	Answers   string
	Comment   string
	Meta      string
}

func (q *Queries) InsertQuestionnaire(ctx context.Context, arg InsertQuestionnaireParams) (int64, error) {
	row := q.queryRow(ctx, q.insertQuestionnaireStmt, insertQuestionnaire,
		arg.UserID,
		arg.QueryType,
		arg.Answers,
		arg.Comment,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isQuizDoneToday = `-- name: IsQuizDoneToday :many
SELECT
  id,
  user_id,
  query_type,
  answers,
  comment,
  "timestamp",
  meta
FROM public.querys
WHERE user_id = $1
  AND query_type    = $2
  AND "timestamp"  >= $3
  AND "timestamp"  <  $4
ORDER BY "timestamp" DESC
`

type IsQuizDoneTodayParams struct {
	UserID      int32
	QueryType   int32
	Timestamp   time.Time
	Timestamp_2 time.Time
}

type IsQuizDoneTodayRow struct {
	ID        int64
	UserID    int32
	QueryType int32
	Answers   string
	Comment   string
	Timestamp time.Time
	Meta      string
}

func (q *Queries) IsQuizDoneToday(ctx context.Context, arg IsQuizDoneTodayParams) ([]IsQuizDoneTodayRow, error) {
	rows, err := q.query(ctx, q.isQuizDoneTodayStmt, isQuizDoneToday,
		arg.UserID,
		arg.QueryType,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IsQuizDoneTodayRow
	for rows.Next() {
		var i IsQuizDoneTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QueryType,
			&i.Answers,
			&i.Comment,
			&i.Timestamp,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInjuryRecoveredByID = `-- name: MarkInjuryRecoveredByID :exec
UPDATE public.injuries
SET status = 1,
    date_end = NOW()
WHERE injury_id = $1
  AND user_id = $2
`

type MarkInjuryRecoveredByIDParams struct {
	InjuryID int32
	UserID   int32
}

func (q *Queries) MarkInjuryRecoveredByID(ctx context.Context, arg MarkInjuryRecoveredByIDParams) error {
	_, err := q.exec(ctx, q.markInjuryRecoveredByIDStmt, markInjuryRecoveredByID, arg.InjuryID, arg.UserID)
	return err
}

const updateQuestionnaireByID = `-- name: UpdateQuestionnaireByID :execrows
UPDATE public.querys
SET answers = $3,
    comment = $4
WHERE user_id = $1
  AND id           = $2
`

type UpdateQuestionnaireByIDParams struct {
	UserID  int32
	ID      int64
	Answers string
	Comment string
}

func (q *Queries) UpdateQuestionnaireByID(ctx context.Context, arg UpdateQuestionnaireByIDParams) (int64, error) {
	result, err := q.exec(ctx, q.updateQuestionnaireByIDStmt, updateQuestionnaireByID,
		arg.UserID,
		arg.ID,
		arg.Answers,
		arg.Comment,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
