// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tietoevrysqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getDeletedUsersStmt, err = db.PrepareContext(ctx, getDeletedUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeletedUsers: %w", err)
	}
	if q.getExerciseHRZonesStmt, err = db.PrepareContext(ctx, getExerciseHRZones); err != nil {
		return nil, fmt.Errorf("error preparing query GetExerciseHRZones: %w", err)
	}
	if q.getExerciseSamplesStmt, err = db.PrepareContext(ctx, getExerciseSamples); err != nil {
		return nil, fmt.Errorf("error preparing query GetExerciseSamples: %w", err)
	}
	if q.getExerciseSectionsStmt, err = db.PrepareContext(ctx, getExerciseSections); err != nil {
		return nil, fmt.Errorf("error preparing query GetExerciseSections: %w", err)
	}
	if q.getExercisesByUserStmt, err = db.PrepareContext(ctx, getExercisesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetExercisesByUser: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.insertActivityZoneStmt, err = db.PrepareContext(ctx, insertActivityZone); err != nil {
		return nil, fmt.Errorf("error preparing query InsertActivityZone: %w", err)
	}
	if q.insertExerciseStmt, err = db.PrepareContext(ctx, insertExercise); err != nil {
		return nil, fmt.Errorf("error preparing query InsertExercise: %w", err)
	}
	if q.insertExerciseHRZoneStmt, err = db.PrepareContext(ctx, insertExerciseHRZone); err != nil {
		return nil, fmt.Errorf("error preparing query InsertExerciseHRZone: %w", err)
	}
	if q.insertExerciseSampleStmt, err = db.PrepareContext(ctx, insertExerciseSample); err != nil {
		return nil, fmt.Errorf("error preparing query InsertExerciseSample: %w", err)
	}
	if q.insertExerciseSectionStmt, err = db.PrepareContext(ctx, insertExerciseSection); err != nil {
		return nil, fmt.Errorf("error preparing query InsertExerciseSection: %w", err)
	}
	if q.insertMeasurementStmt, err = db.PrepareContext(ctx, insertMeasurement); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMeasurement: %w", err)
	}
	if q.insertQuestionnaireAnswerStmt, err = db.PrepareContext(ctx, insertQuestionnaireAnswer); err != nil {
		return nil, fmt.Errorf("error preparing query InsertQuestionnaireAnswer: %w", err)
	}
	if q.insertSymptomStmt, err = db.PrepareContext(ctx, insertSymptom); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSymptom: %w", err)
	}
	if q.insertTestResultStmt, err = db.PrepareContext(ctx, insertTestResult); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTestResult: %w", err)
	}
	if q.logDeletedUserStmt, err = db.PrepareContext(ctx, logDeletedUser); err != nil {
		return nil, fmt.Errorf("error preparing query LogDeletedUser: %w", err)
	}
	if q.upsertUserStmt, err = db.PrepareContext(ctx, upsertUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getDeletedUsersStmt != nil {
		if cerr := q.getDeletedUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeletedUsersStmt: %w", cerr)
		}
	}
	if q.getExerciseHRZonesStmt != nil {
		if cerr := q.getExerciseHRZonesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExerciseHRZonesStmt: %w", cerr)
		}
	}
	if q.getExerciseSamplesStmt != nil {
		if cerr := q.getExerciseSamplesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExerciseSamplesStmt: %w", cerr)
		}
	}
	if q.getExerciseSectionsStmt != nil {
		if cerr := q.getExerciseSectionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExerciseSectionsStmt: %w", cerr)
		}
	}
	if q.getExercisesByUserStmt != nil {
		if cerr := q.getExercisesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExercisesByUserStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.insertActivityZoneStmt != nil {
		if cerr := q.insertActivityZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertActivityZoneStmt: %w", cerr)
		}
	}
	if q.insertExerciseStmt != nil {
		if cerr := q.insertExerciseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertExerciseStmt: %w", cerr)
		}
	}
	if q.insertExerciseHRZoneStmt != nil {
		if cerr := q.insertExerciseHRZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertExerciseHRZoneStmt: %w", cerr)
		}
	}
	if q.insertExerciseSampleStmt != nil {
		if cerr := q.insertExerciseSampleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertExerciseSampleStmt: %w", cerr)
		}
	}
	if q.insertExerciseSectionStmt != nil {
		if cerr := q.insertExerciseSectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertExerciseSectionStmt: %w", cerr)
		}
	}
	if q.insertMeasurementStmt != nil {
		if cerr := q.insertMeasurementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMeasurementStmt: %w", cerr)
		}
	}
	if q.insertQuestionnaireAnswerStmt != nil {
		if cerr := q.insertQuestionnaireAnswerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertQuestionnaireAnswerStmt: %w", cerr)
		}
	}
	if q.insertSymptomStmt != nil {
		if cerr := q.insertSymptomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSymptomStmt: %w", cerr)
		}
	}
	if q.insertTestResultStmt != nil {
		if cerr := q.insertTestResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTestResultStmt: %w", cerr)
		}
	}
	if q.logDeletedUserStmt != nil {
		if cerr := q.logDeletedUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing logDeletedUserStmt: %w", cerr)
		}
	}
	if q.upsertUserStmt != nil {
		if cerr := q.upsertUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	deleteUserStmt                *sql.Stmt
	getDeletedUsersStmt           *sql.Stmt
	getExerciseHRZonesStmt        *sql.Stmt
	getExerciseSamplesStmt        *sql.Stmt
	getExerciseSectionsStmt       *sql.Stmt
	getExercisesByUserStmt        *sql.Stmt
	getUserStmt                   *sql.Stmt
	insertActivityZoneStmt        *sql.Stmt
	insertExerciseStmt            *sql.Stmt
	insertExerciseHRZoneStmt      *sql.Stmt
	insertExerciseSampleStmt      *sql.Stmt
	insertExerciseSectionStmt     *sql.Stmt
	insertMeasurementStmt         *sql.Stmt
	insertQuestionnaireAnswerStmt *sql.Stmt
	insertSymptomStmt             *sql.Stmt
	insertTestResultStmt          *sql.Stmt
	logDeletedUserStmt            *sql.Stmt
	upsertUserStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		deleteUserStmt:                q.deleteUserStmt,
		getDeletedUsersStmt:           q.getDeletedUsersStmt,
		getExerciseHRZonesStmt:        q.getExerciseHRZonesStmt,
		getExerciseSamplesStmt:        q.getExerciseSamplesStmt,
		getExerciseSectionsStmt:       q.getExerciseSectionsStmt,
		getExercisesByUserStmt:        q.getExercisesByUserStmt,
		getUserStmt:                   q.getUserStmt,
		insertActivityZoneStmt:        q.insertActivityZoneStmt,
		insertExerciseStmt:            q.insertExerciseStmt,
		insertExerciseHRZoneStmt:      q.insertExerciseHRZoneStmt,
		insertExerciseSampleStmt:      q.insertExerciseSampleStmt,
		insertExerciseSectionStmt:     q.insertExerciseSectionStmt,
		insertMeasurementStmt:         q.insertMeasurementStmt,
		insertQuestionnaireAnswerStmt: q.insertQuestionnaireAnswerStmt,
		insertSymptomStmt:             q.insertSymptomStmt,
		insertTestResultStmt:          q.insertTestResultStmt,
		logDeletedUserStmt:            q.logDeletedUserStmt,
		upsertUserStmt:                q.upsertUserStmt,
	}
}
