// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tietoevrysqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActivityZone struct {
	UserID         uuid.UUID
	Date           time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SecondsInZone0 sql.NullFloat64
	SecondsInZone1 sql.NullFloat64
	SecondsInZone2 sql.NullFloat64
	SecondsInZone3 sql.NullFloat64
	SecondsInZone4 sql.NullFloat64
	SecondsInZone5 sql.NullFloat64
	Source         string
	RawData        pqtype.NullRawMessage
}

type Exercise struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	UserID            uuid.UUID
	StartTime         time.Time
	Duration          int64
	Comment           sql.NullString
	SportType         sql.NullString
	DetailedSportType sql.NullString
	Distance          sql.NullFloat64
	AvgHeartRate      sql.NullFloat64
	MaxHeartRate      sql.NullFloat64
	Trimp             sql.NullFloat64
	SprintCount       sql.NullInt32
	AvgSpeed          sql.NullFloat64
	MaxSpeed          sql.NullFloat64
	Source            string
	Status            sql.NullString
	Calories          sql.NullInt32
	TrainingLoad      sql.NullInt32
	RawID             sql.NullString
	RawData           pqtype.NullRawMessage
	Feeling           sql.NullInt32
	Recovery          sql.NullInt32
	Rpe               sql.NullInt32
}

type ExerciseHrZone struct {
	ExerciseID    uuid.UUID
	ZoneIndex     int32
	SecondsInZone int32
	LowerLimit    int32
	UpperLimit    int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ExerciseSample struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ExerciseID    uuid.UUID
	SampleType    string
	RecordingRate int32
	Samples       []float64
	Source        string
}

type ExerciseSection struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ExerciseID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	StartTime   time.Time
	EndTime     time.Time
	SectionType sql.NullString
	Name        sql.NullString
	Comment     sql.NullString
	Source      string
	RawID       sql.NullString
	RawData     pqtype.NullRawMessage
}

type Measurement struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserID         uuid.UUID
	Date           time.Time
	Name           string
	NameType       string
	Source         string
	Value          string
	ValueNumeric   sql.NullFloat64
	Comment        sql.NullString
	RawID          sql.NullString
	RawData        pqtype.NullRawMessage
	AdditionalInfo pqtype.NullRawMessage
}

type QuestionAnswer struct {
	UserID                  uuid.UUID
	QuestionnaireInstanceID uuid.UUID
	QuestionnaireNameFi     sql.NullString
	QuestionnaireNameEn     sql.NullString
	QuestionnaireKey        string
	QuestionID              uuid.UUID
	QuestionLabelFi         sql.NullString
	QuestionLabelEn         sql.NullString
	QuestionType            string
	OptionID                uuid.NullUUID
	OptionValue             sql.NullInt32
	OptionLabelFi           sql.NullString
	OptionLabelEn           sql.NullString
	FreeText                sql.NullString
	CreatedAt               time.Time
	UpdatedAt               time.Time
	Value                   pqtype.NullRawMessage
}

type Symptom struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Date           time.Time
	Symptom        string
	Severity       int32
	Comment        sql.NullString
	Source         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RawID          sql.NullString
	OriginalID     uuid.NullUUID
	Recovered      sql.NullBool
	PainIndex      sql.NullInt32
	Side           sql.NullString
	Category       sql.NullString
	AdditionalData pqtype.NullRawMessage
}

type TestResult struct {
	ID                          uuid.UUID
	UserID                      uuid.UUID
	TypeID                      uuid.UUID
	TypeType                    sql.NullString
	TypeResultType              string
	TypeName                    sql.NullString
	Timestamp                   time.Time
	Name                        sql.NullString
	Comment                     sql.NullString
	Data                        json.RawMessage
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	TestEventID                 uuid.NullUUID
	TestEventName               sql.NullString
	TestEventDate               sql.NullTime
	TestEventTemplateTestID     uuid.NullUUID
	TestEventTemplateTestName   sql.NullString
	TestEventTemplateTestLimits pqtype.NullRawMessage
}

type User struct {
	ID                        uuid.UUID
	SporttiID                 int32
	ProfileGender             sql.NullString
	ProfileBirthdate          sql.NullTime
	ProfileWeight             sql.NullFloat64
	ProfileHeight             sql.NullFloat64
	ProfileRestingHeartRate   sql.NullInt32
	ProfileMaximumHeartRate   sql.NullInt32
	ProfileAerobicThreshold   sql.NullInt32
	ProfileAnaerobicThreshold sql.NullInt32
	ProfileVo2max             sql.NullInt32
}
