// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package tietoevrysqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertExercise = `-- name: InsertExercise :exec
INSERT INTO exercises (
    id, created_at, updated_at, user_id, start_time, duration,
    comment, sport_type, detailed_sport_type, distance, avg_heart_rate,
    max_heart_rate, trimp, sprint_count, avg_speed, max_speed,
    source, status, calories, training_load, raw_id,
    feeling, recovery, rpe, raw_data
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21,
    $22, $23, $24, $25
)
ON CONFLICT (source, raw_id) DO NOTHING
`

type InsertExerciseParams struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	UserID            uuid.UUID
	StartTime         time.Time
	Duration          int64
	Comment           sql.NullString
	SportType         sql.NullString
	DetailedSportType sql.NullString
	Distance          sql.NullFloat64
	AvgHeartRate      sql.NullFloat64
	MaxHeartRate      sql.NullFloat64
	Trimp             sql.NullFloat64
	SprintCount       sql.NullInt32
	AvgSpeed          sql.NullFloat64
	MaxSpeed          sql.NullFloat64
	Source            string
	Status            sql.NullString
	Calories          sql.NullInt32
	TrainingLoad      sql.NullInt32
	RawID             sql.NullString
	Feeling           sql.NullInt32
	Recovery          sql.NullInt32
	Rpe               sql.NullInt32
	RawData           pqtype.NullRawMessage
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) error {
	_, err := q.exec(ctx, q.insertExerciseStmt, insertExercise,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.StartTime,
		arg.Duration,
		arg.Comment,
		arg.SportType,
		arg.DetailedSportType,
		arg.Distance,
		arg.AvgHeartRate,
		arg.MaxHeartRate,
		arg.Trimp,
		arg.SprintCount,
		arg.AvgSpeed,
		arg.MaxSpeed,
		arg.Source,
		arg.Status,
		arg.Calories,
		arg.TrainingLoad,
		arg.RawID,
		arg.Feeling,
		arg.Recovery,
		arg.Rpe,
		arg.RawData,
	)
	return err
}

const insertExerciseHRZone = `-- name: InsertExerciseHRZone :exec
INSERT INTO exercise_hr_zones (
    exercise_id, zone_index, seconds_in_zone,
    lower_limit, upper_limit, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
ON CONFLICT (exercise_id, zone_index) DO NOTHING
`

type InsertExerciseHRZoneParams struct {
	ExerciseID    uuid.UUID
	ZoneIndex     int32
	SecondsInZone int32
	LowerLimit    int32
	UpperLimit    int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertExerciseHRZone(ctx context.Context, arg InsertExerciseHRZoneParams) error {
	_, err := q.exec(ctx, q.insertExerciseHRZoneStmt, insertExerciseHRZone,
		arg.ExerciseID,
		arg.ZoneIndex,
		arg.SecondsInZone,
		arg.LowerLimit,
		arg.UpperLimit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertExerciseSample = `-- name: InsertExerciseSample :exec
INSERT INTO exercise_samples (
    id, user_id, exercise_id,
    sample_type, recording_rate, samples, source
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
ON CONFLICT (exercise_id, sample_type) DO NOTHING
`

type InsertExerciseSampleParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ExerciseID    uuid.UUID
	SampleType    string
	RecordingRate int32
	Samples       []float64
	Source        string
}

func (q *Queries) InsertExerciseSample(ctx context.Context, arg InsertExerciseSampleParams) error {
	_, err := q.exec(ctx, q.insertExerciseSampleStmt, insertExerciseSample,
		arg.ID,
		arg.UserID,
		arg.ExerciseID,
		arg.SampleType,
		arg.RecordingRate,
		pq.Array(arg.Samples),
		arg.Source,
	)
	return err
}

const insertExerciseSection = `-- name: InsertExerciseSection :exec
INSERT INTO exercise_sections (
    id, user_id, exercise_id,
    created_at, updated_at, start_time, end_time,
    section_type, name, comment, source, raw_id, raw_data
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO NOTHING
`

type InsertExerciseSectionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ExerciseID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	StartTime   time.Time
	EndTime     time.Time
	SectionType sql.NullString
	Name        sql.NullString
	Comment     sql.NullString
	Source      string
	RawID       sql.NullString
	RawData     pqtype.NullRawMessage
}

func (q *Queries) InsertExerciseSection(ctx context.Context, arg InsertExerciseSectionParams) error {
	_, err := q.exec(ctx, q.insertExerciseSectionStmt, insertExerciseSection,
		arg.ID,
		arg.UserID,
		arg.ExerciseID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartTime,
		arg.EndTime,
		arg.SectionType,
		arg.Name,
		arg.Comment,
		arg.Source,
		arg.RawID,
		arg.RawData,
	)
	return err
}

const insertMeasurement = `-- name: InsertMeasurement :exec
INSERT INTO measurements (
    id, created_at, updated_at, user_id, date, name, name_type,
    source, value, value_numeric, comment, raw_id, raw_data, additional_info
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (source, user_id, date, name, raw_id) DO NOTHING
`

type InsertMeasurementParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserID         uuid.UUID
	Date           time.Time
	Name           string
	NameType       string
	Source         string
	Value          string
	ValueNumeric   sql.NullFloat64
	Comment        sql.NullString
	RawID          sql.NullString
	RawData        pqtype.NullRawMessage
	AdditionalInfo pqtype.NullRawMessage
}

func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error {
	_, err := q.exec(ctx, q.insertMeasurementStmt, insertMeasurement,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Date,
		arg.Name,
		arg.NameType,
		arg.Source,
		arg.Value,
		arg.ValueNumeric,
		arg.Comment,
		arg.RawID,
		arg.RawData,
		arg.AdditionalInfo,
	)
	return err
}

const insertQuestionnaireAnswer = `-- name: InsertQuestionnaireAnswer :exec
INSERT INTO question_answers (
    user_id, questionnaire_instance_id, questionnaire_name_fi,
    questionnaire_name_en, questionnaire_key, question_id, question_label_fi,
    question_label_en, question_type, option_id, option_value,
    option_label_fi, option_label_en, free_text, created_at, updated_at, value
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
ON CONFLICT (user_id, questionnaire_instance_id, question_id) DO NOTHING
`

type InsertQuestionnaireAnswerParams struct {
	UserID                  uuid.UUID
	QuestionnaireInstanceID uuid.UUID
	QuestionnaireNameFi     sql.NullString
	QuestionnaireNameEn     sql.NullString
	QuestionnaireKey        string
	QuestionID              uuid.UUID
	QuestionLabelFi         sql.NullString
	QuestionLabelEn         sql.NullString
	QuestionType            string
	OptionID                uuid.NullUUID
	OptionValue             sql.NullInt32
	OptionLabelFi           sql.NullString
	OptionLabelEn           sql.NullString
	FreeText                sql.NullString
	CreatedAt               time.Time
	UpdatedAt               time.Time
	Value                   pqtype.NullRawMessage
}

func (q *Queries) InsertQuestionnaireAnswer(ctx context.Context, arg InsertQuestionnaireAnswerParams) error {
	_, err := q.exec(ctx, q.insertQuestionnaireAnswerStmt, insertQuestionnaireAnswer,
		arg.UserID,
		arg.QuestionnaireInstanceID,
		arg.QuestionnaireNameFi,
		arg.QuestionnaireNameEn,
		arg.QuestionnaireKey,
		arg.QuestionID,
		arg.QuestionLabelFi,
		arg.QuestionLabelEn,
		arg.QuestionType,
		arg.OptionID,
		arg.OptionValue,
		arg.OptionLabelFi,
		arg.OptionLabelEn,
		arg.FreeText,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Value,
	)
	return err
}

const insertSymptom = `-- name: InsertSymptom :exec
INSERT INTO symptoms (
    id, user_id, date, symptom, severity, comment, source,
    created_at, updated_at, raw_id, original_id, recovered,
    pain_index, side, category, additional_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16
)
ON CONFLICT (source, user_id, date, raw_id) DO NOTHING
`

type InsertSymptomParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Date           time.Time
	Symptom        string
	Severity       int32
	Comment        sql.NullString
	Source         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RawID          sql.NullString
	OriginalID     uuid.NullUUID
	Recovered      sql.NullBool
	PainIndex      sql.NullInt32
	Side           sql.NullString
	Category       sql.NullString
	AdditionalData pqtype.NullRawMessage
}

func (q *Queries) InsertSymptom(ctx context.Context, arg InsertSymptomParams) error {
	_, err := q.exec(ctx, q.insertSymptomStmt, insertSymptom,
		arg.ID,
		arg.UserID,
		arg.Date,
		arg.Symptom,
		arg.Severity,
		arg.Comment,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RawID,
		arg.OriginalID,
		arg.Recovered,
		arg.PainIndex,
		arg.Side,
		arg.Category,
		arg.AdditionalData,
	)
	return err
}

const insertTestResult = `-- name: InsertTestResult :exec
INSERT INTO test_results (
    id, user_id, type_id, type_type, type_result_type, type_name,
    timestamp, name, comment, data, created_at, updated_at,
    test_event_id, test_event_name, test_event_date,
    test_event_template_test_id, test_event_template_test_name,
    test_event_template_test_limits
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
ON CONFLICT (id) DO NOTHING
`

type InsertTestResultParams struct {
	ID                          uuid.UUID
	UserID                      uuid.UUID
	TypeID                      uuid.UUID
	TypeType                    sql.NullString
	TypeResultType              string
	TypeName                    sql.NullString
	Timestamp                   time.Time
	Name                        sql.NullString
	Comment                     sql.NullString
	Data                        json.RawMessage
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	TestEventID                 uuid.NullUUID
	TestEventName               sql.NullString
	TestEventDate               sql.NullTime
	TestEventTemplateTestID     uuid.NullUUID
	TestEventTemplateTestName   sql.NullString
	TestEventTemplateTestLimits pqtype.NullRawMessage
}

func (q *Queries) InsertTestResult(ctx context.Context, arg InsertTestResultParams) error {
	_, err := q.exec(ctx, q.insertTestResultStmt, insertTestResult,
		arg.ID,
		arg.UserID,
		arg.TypeID,
		arg.TypeType,
		arg.TypeResultType,
		arg.TypeName,
		arg.Timestamp,
		arg.Name,
		arg.Comment,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TestEventID,
		arg.TestEventName,
		arg.TestEventDate,
		arg.TestEventTemplateTestID,
		arg.TestEventTemplateTestName,
		arg.TestEventTemplateTestLimits,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (
    id, sportti_id, profile_gender, profile_birthdate, profile_weight,
    profile_height, profile_resting_heart_rate, profile_maximum_heart_rate,
    profile_aerobic_threshold, profile_anaerobic_threshold, profile_vo2max
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    sportti_id = EXCLUDED.sportti_id,
    profile_gender = EXCLUDED.profile_gender,
    profile_birthdate = EXCLUDED.profile_birthdate,
    profile_weight = EXCLUDED.profile_weight,
    profile_height = EXCLUDED.profile_height,
    profile_resting_heart_rate = EXCLUDED.profile_resting_heart_rate,
    profile_maximum_heart_rate = EXCLUDED.profile_maximum_heart_rate,
    profile_aerobic_threshold = EXCLUDED.profile_aerobic_threshold,
    profile_anaerobic_threshold = EXCLUDED.profile_anaerobic_threshold,
    profile_vo2max = EXCLUDED.profile_vo2max
`

type UpsertUserParams struct {
	ID                        uuid.UUID
	SporttiID                 int32
	ProfileGender             sql.NullString
	ProfileBirthdate          sql.NullTime
	ProfileWeight             sql.NullFloat64
	ProfileHeight             sql.NullFloat64
	ProfileRestingHeartRate   sql.NullInt32
	ProfileMaximumHeartRate   sql.NullInt32
	ProfileAerobicThreshold   sql.NullInt32
	ProfileAnaerobicThreshold sql.NullInt32
	ProfileVo2max             sql.NullInt32
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.exec(ctx, q.upsertUserStmt, upsertUser,
		arg.ID,
		arg.SporttiID,
		arg.ProfileGender,
		arg.ProfileBirthdate,
		arg.ProfileWeight,
		arg.ProfileHeight,
		arg.ProfileRestingHeartRate,
		arg.ProfileMaximumHeartRate,
		arg.ProfileAerobicThreshold,
		arg.ProfileAnaerobicThreshold,
		arg.ProfileVo2max,
	)
	return err
}
