// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package tietoevrysqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (
    id, sportti_id, profile_gender, profile_birthdate, profile_weight,
    profile_height, profile_resting_heart_rate, profile_maximum_heart_rate,
    profile_aerobic_threshold, profile_anaerobic_threshold, profile_vo2max
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    sportti_id = EXCLUDED.sportti_id,
    profile_gender = EXCLUDED.profile_gender,
    profile_birthdate = EXCLUDED.profile_birthdate,
    profile_weight = EXCLUDED.profile_weight,
    profile_height = EXCLUDED.profile_height,
    profile_resting_heart_rate = EXCLUDED.profile_resting_heart_rate,
    profile_maximum_heart_rate = EXCLUDED.profile_maximum_heart_rate,
    profile_aerobic_threshold = EXCLUDED.profile_aerobic_threshold,
    profile_anaerobic_threshold = EXCLUDED.profile_anaerobic_threshold,
    profile_vo2max = EXCLUDED.profile_vo2max
`

type UpsertUserParams struct {
	ID                        uuid.UUID
	SporttiID                 int32
	ProfileGender             sql.NullString
	ProfileBirthdate          sql.NullTime
	ProfileWeight             sql.NullFloat64
	ProfileHeight             sql.NullFloat64
	ProfileRestingHeartRate   sql.NullInt32
	ProfileMaximumHeartRate   sql.NullInt32
	ProfileAerobicThreshold   sql.NullInt32
	ProfileAnaerobicThreshold sql.NullInt32
	ProfileVo2max             sql.NullInt32
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.exec(ctx, q.upsertUserStmt, upsertUser,
		arg.ID,
		arg.SporttiID,
		arg.ProfileGender,
		arg.ProfileBirthdate,
		arg.ProfileWeight,
		arg.ProfileHeight,
		arg.ProfileRestingHeartRate,
		arg.ProfileMaximumHeartRate,
		arg.ProfileAerobicThreshold,
		arg.ProfileAnaerobicThreshold,
		arg.ProfileVo2max,
	)
	return err
}
