package fis

import (
	"time"

	fissqlc "github.com/DeRuina/KUHA-REST-API/internal/db/fis"
	"github.com/DeRuina/KUHA-REST-API/internal/utils"
)

type InsertRaceCCClean struct {
	Raceid            int32
	Eventid           *int32
	Seasoncode        *int32
	Racecodex         *int32
	Disciplineid      *string
	Disciplinecode    *string
	Catcode           *string
	Catcode2          *string
	Catcode3          *string
	Catcode4          *string
	Gender            *string
	Racedate          *time.Time
	Starteventdate    *time.Time
	Description       *string
	Place             *string
	Nationcode        *string
	Receiveddate      *time.Time
	Validdate         *time.Time
	Td1id             *int32
	Td1name           *string
	Td1nation         *string
	Td1code           *int32
	Td2id             *int32
	Td2name           *string
	Td2nation         *string
	Td2code           *int32
	Calstatuscode     *string
	Procstatuscode    *string
	Displaystatus     *string
	Fisinterncomment  *string
	Webcomment        *string
	Pursuit           *string
	Masse             *string
	Relay             *string
	Distance          *string
	Hill              *string
	Style             *string
	Qualif            *string
	Finale            *string
	Homol             *string
	Published         *int32
	Validforfispoints *int32
	Usedfislist       *string
	Tolist            *string
	Discforlistcode   *string
	Calculatedpenalty *string
	Appliedpenalty    *string
	Appliedscala      *string
	Penscafixed       *string
	Version           *int32
	Nationraceid      *int32
	Provraceid        *int32
	Msql7evid         *int32
	Mssql7id          *int32
	Topbanner         *string
	Bottombanner      *string
	Toplogo           *string
	Bottomlogo        *string
	Gallery           *string
	Indi              *int32
	Team              *int32
	Tabcount          *int32
	Columncount       *int32
	Level             *string
	Hloc1             *string
	Hloc2             *string
	Hloc3             *string
	Hcet1             *string
	Hcet2             *string
	Hcet3             *string
	Live              *int32
	Livestatus1       *string
	Livestatus2       *string
	Livestatus3       *string
	Liveinfo1         *string
	Liveinfo2         *string
	Liveinfo3         *string
	Passwd            *string
	Timinglogo        *string
	Results           *int32
	Pdf               *int32
	Noepr             *int32
	Tddoc             *int32
	Timingreport      *int32
	SpecialCupPoints  *int32
	SkipWcsl          *int32
	Validforowg       *int32
	Lastupdate        *time.Time
}

type UpdateRaceCCClean = InsertRaceCCClean

func mapInsertRaceCCToParams(in InsertRaceCCClean) fissqlc.InsertRaceCCParams {
	return fissqlc.InsertRaceCCParams{
		Raceid:            in.Raceid,
		Eventid:           utils.NullInt32Ptr(in.Eventid),
		Seasoncode:        utils.NullInt32Ptr(in.Seasoncode),
		Racecodex:         utils.NullInt32Ptr(in.Racecodex),
		Disciplineid:      utils.NullStringPtr(in.Disciplineid),
		Disciplinecode:    utils.NullStringPtr(in.Disciplinecode),
		Catcode:           utils.NullStringPtr(in.Catcode),
		Catcode2:          utils.NullStringPtr(in.Catcode2),
		Catcode3:          utils.NullStringPtr(in.Catcode3),
		Catcode4:          utils.NullStringPtr(in.Catcode4),
		Gender:            utils.NullStringPtr(in.Gender),
		Racedate:          utils.NullTimePtr(in.Racedate),
		Starteventdate:    utils.NullTimePtr(in.Starteventdate),
		Description:       utils.NullStringPtr(in.Description),
		Place:             utils.NullStringPtr(in.Place),
		Nationcode:        utils.NullStringPtr(in.Nationcode),
		Receiveddate:      utils.NullTimePtr(in.Receiveddate),
		Validdate:         utils.NullTimePtr(in.Validdate),
		Td1id:             utils.NullInt32Ptr(in.Td1id),
		Td1name:           utils.NullStringPtr(in.Td1name),
		Td1nation:         utils.NullStringPtr(in.Td1nation),
		Td1code:           utils.NullInt32Ptr(in.Td1code),
		Td2id:             utils.NullInt32Ptr(in.Td2id),
		Td2name:           utils.NullStringPtr(in.Td2name),
		Td2nation:         utils.NullStringPtr(in.Td2nation),
		Td2code:           utils.NullInt32Ptr(in.Td2code),
		Calstatuscode:     utils.NullStringPtr(in.Calstatuscode),
		Procstatuscode:    utils.NullStringPtr(in.Procstatuscode),
		Displaystatus:     utils.NullStringPtr(in.Displaystatus),
		Fisinterncomment:  utils.NullStringPtr(in.Fisinterncomment),
		Webcomment:        utils.NullStringPtr(in.Webcomment),
		Pursuit:           utils.NullStringPtr(in.Pursuit),
		Masse:             utils.NullStringPtr(in.Masse),
		Relay:             utils.NullStringPtr(in.Relay),
		Distance:          utils.NullStringPtr(in.Distance),
		Hill:              utils.NullStringPtr(in.Hill),
		Style:             utils.NullStringPtr(in.Style),
		Qualif:            utils.NullStringPtr(in.Qualif),
		Finale:            utils.NullStringPtr(in.Finale),
		Homol:             utils.NullStringPtr(in.Homol),
		Published:         utils.NullInt32Ptr(in.Published),
		Validforfispoints: utils.NullInt32Ptr(in.Validforfispoints),
		Usedfislist:       utils.NullStringPtr(in.Usedfislist),
		Tolist:            utils.NullStringPtr(in.Tolist),
		Discforlistcode:   utils.NullStringPtr(in.Discforlistcode),
		Calculatedpenalty: utils.NullStringPtr(in.Calculatedpenalty),
		Appliedpenalty:    utils.NullStringPtr(in.Appliedpenalty),
		Appliedscala:      utils.NullStringPtr(in.Appliedscala),
		Penscafixed:       utils.NullStringPtr(in.Penscafixed),
		Version:           utils.NullInt32Ptr(in.Version),
		Nationraceid:      utils.NullInt32Ptr(in.Nationraceid),
		Provraceid:        utils.NullInt32Ptr(in.Provraceid),
		Msql7evid:         utils.NullInt32Ptr(in.Msql7evid),
		Mssql7id:          utils.NullInt32Ptr(in.Mssql7id),
		Topbanner:         utils.NullStringPtr(in.Topbanner),
		Bottombanner:      utils.NullStringPtr(in.Bottombanner),
		Toplogo:           utils.NullStringPtr(in.Toplogo),
		Bottomlogo:        utils.NullStringPtr(in.Bottomlogo),
		Gallery:           utils.NullStringPtr(in.Gallery),
		Indi:              utils.NullInt32Ptr(in.Indi),
		Team:              utils.NullInt32Ptr(in.Team),
		Tabcount:          utils.NullInt32Ptr(in.Tabcount),
		Columncount:       utils.NullInt32Ptr(in.Columncount),
		Level:             utils.NullStringPtr(in.Level),
		Hloc1:             utils.NullStringPtr(in.Hloc1),
		Hloc2:             utils.NullStringPtr(in.Hloc2),
		Hloc3:             utils.NullStringPtr(in.Hloc3),
		Hcet1:             utils.NullStringPtr(in.Hcet1),
		Hcet2:             utils.NullStringPtr(in.Hcet2),
		Hcet3:             utils.NullStringPtr(in.Hcet3),
		Live:              utils.NullInt32Ptr(in.Live),
		Livestatus1:       utils.NullStringPtr(in.Livestatus1),
		Livestatus2:       utils.NullStringPtr(in.Livestatus2),
		Livestatus3:       utils.NullStringPtr(in.Livestatus3),
		Liveinfo1:         utils.NullStringPtr(in.Liveinfo1),
		Liveinfo2:         utils.NullStringPtr(in.Liveinfo2),
		Liveinfo3:         utils.NullStringPtr(in.Liveinfo3),
		Passwd:            utils.NullStringPtr(in.Passwd),
		Timinglogo:        utils.NullStringPtr(in.Timinglogo),
		Results:           utils.NullInt32Ptr(in.Results),
		Pdf:               utils.NullInt32Ptr(in.Pdf),
		Noepr:             utils.NullInt32Ptr(in.Noepr),
		Tddoc:             utils.NullInt32Ptr(in.Tddoc),
		Timingreport:      utils.NullInt32Ptr(in.Timingreport),
		SpecialCupPoints:  utils.NullInt32Ptr(in.SpecialCupPoints),
		SkipWcsl:          utils.NullInt32Ptr(in.SkipWcsl),
		Validforowg:       utils.NullInt32Ptr(in.Validforowg),
		Lastupdate:        utils.NullTimePtr(in.Lastupdate),
	}
}

func mapUpdateRaceCCToParams(in UpdateRaceCCClean) fissqlc.UpdateRaceCCByIDParams {
	// same mapping as insert, but to UpdateRaceCCByIDParams
	p := mapInsertRaceCCToParams(InsertRaceCCClean(in))
	return fissqlc.UpdateRaceCCByIDParams{
		Raceid:            p.Raceid,
		Eventid:           p.Eventid,
		Seasoncode:        p.Seasoncode,
		Racecodex:         p.Racecodex,
		Disciplineid:      p.Disciplineid,
		Disciplinecode:    p.Disciplinecode,
		Catcode:           p.Catcode,
		Catcode2:          p.Catcode2,
		Catcode3:          p.Catcode3,
		Catcode4:          p.Catcode4,
		Gender:            p.Gender,
		Racedate:          p.Racedate,
		Starteventdate:    p.Starteventdate,
		Description:       p.Description,
		Place:             p.Place,
		Nationcode:        p.Nationcode,
		Td1id:             p.Td1id,
		Td1name:           p.Td1name,
		Td1nation:         p.Td1nation,
		Td1code:           p.Td1code,
		Td2id:             p.Td2id,
		Td2name:           p.Td2name,
		Td2nation:         p.Td2nation,
		Td2code:           p.Td2code,
		Calstatuscode:     p.Calstatuscode,
		Procstatuscode:    p.Procstatuscode,
		Receiveddate:      p.Receiveddate,
		Pursuit:           p.Pursuit,
		Masse:             p.Masse,
		Relay:             p.Relay,
		Distance:          p.Distance,
		Hill:              p.Hill,
		Style:             p.Style,
		Qualif:            p.Qualif,
		Finale:            p.Finale,
		Homol:             p.Homol,
		Webcomment:        p.Webcomment,
		Displaystatus:     p.Displaystatus,
		Fisinterncomment:  p.Fisinterncomment,
		Published:         p.Published,
		Validforfispoints: p.Validforfispoints,
		Usedfislist:       p.Usedfislist,
		Tolist:            p.Tolist,
		Discforlistcode:   p.Discforlistcode,
		Calculatedpenalty: p.Calculatedpenalty,
		Appliedpenalty:    p.Appliedpenalty,
		Appliedscala:      p.Appliedscala,
		Penscafixed:       p.Penscafixed,
		Version:           p.Version,
		Nationraceid:      p.Nationraceid,
		Provraceid:        p.Provraceid,
		Msql7evid:         p.Msql7evid,
		Mssql7id:          p.Mssql7id,
		Results:           p.Results,
		Pdf:               p.Pdf,
		Topbanner:         p.Topbanner,
		Bottombanner:      p.Bottombanner,
		Toplogo:           p.Toplogo,
		Bottomlogo:        p.Bottomlogo,
		Gallery:           p.Gallery,
		Indi:              p.Indi,
		Team:              p.Team,
		Tabcount:          p.Tabcount,
		Columncount:       p.Columncount,
		Level:             p.Level,
		Hloc1:             p.Hloc1,
		Hloc2:             p.Hloc2,
		Hloc3:             p.Hloc3,
		Hcet1:             p.Hcet1,
		Hcet2:             p.Hcet2,
		Hcet3:             p.Hcet3,
		Live:              p.Live,
		Livestatus1:       p.Livestatus1,
		Livestatus2:       p.Livestatus2,
		Livestatus3:       p.Livestatus3,
		Liveinfo1:         p.Liveinfo1,
		Liveinfo2:         p.Liveinfo2,
		Liveinfo3:         p.Liveinfo3,
		Passwd:            p.Passwd,
		Timinglogo:        p.Timinglogo,
		Validdate:         p.Validdate,
		Noepr:             p.Noepr,
		Tddoc:             p.Tddoc,
		Timingreport:      p.Timingreport,
		SpecialCupPoints:  p.SpecialCupPoints,
		SkipWcsl:          p.SkipWcsl,
		Validforowg:       p.Validforowg,
		Lastupdate:        p.Lastupdate,
	}
}
