// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package klabsqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getAllSporttiIDsStmt, err = db.PrepareContext(ctx, getAllSporttiIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSporttiIDs: %w", err)
	}
	if q.insertCustomerStmt, err = db.PrepareContext(ctx, insertCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query InsertCustomer: %w", err)
	}
	if q.insertDirRawDataStmt, err = db.PrepareContext(ctx, insertDirRawData); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirRawData: %w", err)
	}
	if q.insertDirReportStmt, err = db.PrepareContext(ctx, insertDirReport); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirReport: %w", err)
	}
	if q.insertDirResultsStmt, err = db.PrepareContext(ctx, insertDirResults); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirResults: %w", err)
	}
	if q.insertDirTestStmt, err = db.PrepareContext(ctx, insertDirTest); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirTest: %w", err)
	}
	if q.insertDirTestStepStmt, err = db.PrepareContext(ctx, insertDirTestStep); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDirTestStep: %w", err)
	}
	if q.insertMeasurementStmt, err = db.PrepareContext(ctx, insertMeasurement); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMeasurement: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getAllSporttiIDsStmt != nil {
		if cerr := q.getAllSporttiIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSporttiIDsStmt: %w", cerr)
		}
	}
	if q.insertCustomerStmt != nil {
		if cerr := q.insertCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertCustomerStmt: %w", cerr)
		}
	}
	if q.insertDirRawDataStmt != nil {
		if cerr := q.insertDirRawDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirRawDataStmt: %w", cerr)
		}
	}
	if q.insertDirReportStmt != nil {
		if cerr := q.insertDirReportStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirReportStmt: %w", cerr)
		}
	}
	if q.insertDirResultsStmt != nil {
		if cerr := q.insertDirResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirResultsStmt: %w", cerr)
		}
	}
	if q.insertDirTestStmt != nil {
		if cerr := q.insertDirTestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirTestStmt: %w", cerr)
		}
	}
	if q.insertDirTestStepStmt != nil {
		if cerr := q.insertDirTestStepStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDirTestStepStmt: %w", cerr)
		}
	}
	if q.insertMeasurementStmt != nil {
		if cerr := q.insertMeasurementStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMeasurementStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	getAllSporttiIDsStmt  *sql.Stmt
	insertCustomerStmt    *sql.Stmt
	insertDirRawDataStmt  *sql.Stmt
	insertDirReportStmt   *sql.Stmt
	insertDirResultsStmt  *sql.Stmt
	insertDirTestStmt     *sql.Stmt
	insertDirTestStepStmt *sql.Stmt
	insertMeasurementStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		getAllSporttiIDsStmt:  q.getAllSporttiIDsStmt,
		insertCustomerStmt:    q.insertCustomerStmt,
		insertDirRawDataStmt:  q.insertDirRawDataStmt,
		insertDirReportStmt:   q.insertDirReportStmt,
		insertDirResultsStmt:  q.insertDirResultsStmt,
		insertDirTestStmt:     q.insertDirTestStmt,
		insertDirTestStepStmt: q.insertDirTestStepStmt,
		insertMeasurementStmt: q.insertMeasurementStmt,
	}
}
