// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package klabsqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getAllSporttiIDs = `-- name: GetAllSporttiIDs :many
SELECT sportti_id FROM sportti_id_list
`

func (q *Queries) GetAllSporttiIDs(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.getAllSporttiIDsStmt, getAllSporttiIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sportti_id string
		if err := rows.Scan(&sportti_id); err != nil {
			return nil, err
		}
		items = append(items, sportti_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT idcustomer, firstname, lastname, idgroups, dob, sex, dob_year, dob_month, dob_day, pid_number, company, occupation, education, address, phone_home, phone_work, phone_mobile, faxno, email, username, password, readonly, warnings, allow_to_save, allow_to_cloud, flag2, idsport, medication, addinfo, team_name, add1, athlete, add10, add20, updatemode, weight_kg, height_cm, date_modified, recom_testlevel, created_by, mod_by, mod_date, deleted, created_date, modded, allow_anonymous_data, locked, allow_to_sprintai, tosprintai_from, stat_sent, sportti_id FROM customer
WHERE idcustomer = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, idcustomer int32) (Customer, error) {
	row := q.queryRow(ctx, q.getCustomerByIDStmt, getCustomerByID, idcustomer)
	var i Customer
	err := row.Scan(
		&i.Idcustomer,
		&i.Firstname,
		&i.Lastname,
		&i.Idgroups,
		&i.Dob,
		&i.Sex,
		&i.DobYear,
		&i.DobMonth,
		&i.DobDay,
		&i.PidNumber,
		&i.Company,
		&i.Occupation,
		&i.Education,
		&i.Address,
		&i.PhoneHome,
		&i.PhoneWork,
		&i.PhoneMobile,
		&i.Faxno,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Readonly,
		&i.Warnings,
		&i.AllowToSave,
		&i.AllowToCloud,
		&i.Flag2,
		&i.Idsport,
		&i.Medication,
		&i.Addinfo,
		&i.TeamName,
		&i.Add1,
		&i.Athlete,
		&i.Add10,
		&i.Add20,
		&i.Updatemode,
		&i.WeightKg,
		&i.HeightCm,
		&i.DateModified,
		&i.RecomTestlevel,
		&i.CreatedBy,
		&i.ModBy,
		&i.ModDate,
		&i.Deleted,
		&i.CreatedDate,
		&i.Modded,
		&i.AllowAnonymousData,
		&i.Locked,
		&i.AllowToSprintai,
		&i.TosprintaiFrom,
		&i.StatSent,
		&i.SporttiID,
	)
	return i, err
}

const getDirRawDataByMeasurementIDs = `-- name: GetDirRawDataByMeasurementIDs :many
SELECT iddirrawdata, idmeasurement, rawdata, columndata, info, unitsdata, created_by, mod_by, mod_date, deleted, created_date, modded
FROM dirrawdata
WHERE idmeasurement = ANY($1::int[])
ORDER BY idmeasurement
`

func (q *Queries) GetDirRawDataByMeasurementIDs(ctx context.Context, dollar_1 []int32) ([]Dirrawdatum, error) {
	rows, err := q.query(ctx, q.getDirRawDataByMeasurementIDsStmt, getDirRawDataByMeasurementIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dirrawdatum
	for rows.Next() {
		var i Dirrawdatum
		if err := rows.Scan(
			&i.Iddirrawdata,
			&i.Idmeasurement,
			&i.Rawdata,
			&i.Columndata,
			&i.Info,
			&i.Unitsdata,
			&i.CreatedBy,
			&i.ModBy,
			&i.ModDate,
			&i.Deleted,
			&i.CreatedDate,
			&i.Modded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirReportsByMeasurementIDs = `-- name: GetDirReportsByMeasurementIDs :many
SELECT iddirreport, page_instructions, idmeasurement, template_rec, librec_name, created_by, mod_by, mod_date, deleted, created_date, modded
FROM dirreport
WHERE idmeasurement = ANY($1::int[])
ORDER BY idmeasurement
`

func (q *Queries) GetDirReportsByMeasurementIDs(ctx context.Context, dollar_1 []int32) ([]Dirreport, error) {
	rows, err := q.query(ctx, q.getDirReportsByMeasurementIDsStmt, getDirReportsByMeasurementIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dirreport
	for rows.Next() {
		var i Dirreport
		if err := rows.Scan(
			&i.Iddirreport,
			&i.PageInstructions,
			&i.Idmeasurement,
			&i.TemplateRec,
			&i.LibrecName,
			&i.CreatedBy,
			&i.ModBy,
			&i.ModDate,
			&i.Deleted,
			&i.CreatedDate,
			&i.Modded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirResultsByMeasurementIDs = `-- name: GetDirResultsByMeasurementIDs :many
SELECT iddirresults, idmeasurement, max_vo2mlkgmin, max_vo2mlmin, max_vo2, max_hr, max_speed, max_pace, max_p, max_pkg, max_angle, max_lac, max_add1, max_add2, max_add3, lac_ank_vo2mlkgmin, lac_ank_vo2mlmin, lac_ank_vo2, lac_ank_vo2pr, lac_ank_hr, lac_ank_speed, lac_ank_pace, lac_ank_p, lac_ank_pkg, lac_ank_angle, lac_ank_lac, lac_ank_add1, lac_ank_add2, lac_ank_add3, lac_aerk_vo2mlkgmin, lac_aerk_vo2mlmin, lac_aerk_vo2, lac_aerk_vo2pr, lac_aerk_hr, lac_aerk_speed, lac_aerk_pace, lac_aerk_p, lac_aerk_pkg, lac_aerk_angle, lac_aerk_lac, lac_aerk_add1, lac_aerk_add2, lac_aerk_add3, vent_ank_vo2mlkgmin, vent_ank_vo2mlmin, vent_ank_vo2, vent_ank_vo2pr, vent_ank_hr, vent_ank_speed, vent_ank_pace, vent_ank_p, vent_ank_pkg, vent_ank_angle, vent_ank_lac, vent_ank_add1, vent_ank_add2, vent_ank_add3, vent_aerk_vo2mlkgmin, vent_aerk_vo2mlmin, vent_aerk_vo2, vent_aerk_vo2pr, vent_aerk_hr, vent_aerk_speed, vent_aerk_pace, vent_aerk_p, vent_aerk_pkg, vent_aerk_angle, vent_aerk_lac, vent_aerk_add1, vent_aerk_add2, vent_aerk_add3, created_by, mod_by, mod_date, deleted, created_date, modded
FROM dirresults
WHERE idmeasurement = ANY($1::int[])
ORDER BY idmeasurement
`

func (q *Queries) GetDirResultsByMeasurementIDs(ctx context.Context, dollar_1 []int32) ([]Dirresult, error) {
	rows, err := q.query(ctx, q.getDirResultsByMeasurementIDsStmt, getDirResultsByMeasurementIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dirresult
	for rows.Next() {
		var i Dirresult
		if err := rows.Scan(
			&i.Iddirresults,
			&i.Idmeasurement,
			&i.MaxVo2mlkgmin,
			&i.MaxVo2mlmin,
			&i.MaxVo2,
			&i.MaxHr,
			&i.MaxSpeed,
			&i.MaxPace,
			&i.MaxP,
			&i.MaxPkg,
			&i.MaxAngle,
			&i.MaxLac,
			&i.MaxAdd1,
			&i.MaxAdd2,
			&i.MaxAdd3,
			&i.LacAnkVo2mlkgmin,
			&i.LacAnkVo2mlmin,
			&i.LacAnkVo2,
			&i.LacAnkVo2pr,
			&i.LacAnkHr,
			&i.LacAnkSpeed,
			&i.LacAnkPace,
			&i.LacAnkP,
			&i.LacAnkPkg,
			&i.LacAnkAngle,
			&i.LacAnkLac,
			&i.LacAnkAdd1,
			&i.LacAnkAdd2,
			&i.LacAnkAdd3,
			&i.LacAerkVo2mlkgmin,
			&i.LacAerkVo2mlmin,
			&i.LacAerkVo2,
			&i.LacAerkVo2pr,
			&i.LacAerkHr,
			&i.LacAerkSpeed,
			&i.LacAerkPace,
			&i.LacAerkP,
			&i.LacAerkPkg,
			&i.LacAerkAngle,
			&i.LacAerkLac,
			&i.LacAerkAdd1,
			&i.LacAerkAdd2,
			&i.LacAerkAdd3,
			&i.VentAnkVo2mlkgmin,
			&i.VentAnkVo2mlmin,
			&i.VentAnkVo2,
			&i.VentAnkVo2pr,
			&i.VentAnkHr,
			&i.VentAnkSpeed,
			&i.VentAnkPace,
			&i.VentAnkP,
			&i.VentAnkPkg,
			&i.VentAnkAngle,
			&i.VentAnkLac,
			&i.VentAnkAdd1,
			&i.VentAnkAdd2,
			&i.VentAnkAdd3,
			&i.VentAerkVo2mlkgmin,
			&i.VentAerkVo2mlmin,
			&i.VentAerkVo2,
			&i.VentAerkVo2pr,
			&i.VentAerkHr,
			&i.VentAerkSpeed,
			&i.VentAerkPace,
			&i.VentAerkP,
			&i.VentAerkPkg,
			&i.VentAerkAngle,
			&i.VentAerkLac,
			&i.VentAerkAdd1,
			&i.VentAerkAdd2,
			&i.VentAerkAdd3,
			&i.CreatedBy,
			&i.ModBy,
			&i.ModDate,
			&i.Deleted,
			&i.CreatedDate,
			&i.Modded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirTestStepsByMeasurementIDs = `-- name: GetDirTestStepsByMeasurementIDs :many
SELECT iddirteststeps, idmeasurement, stepno, ana_time, timestop, speed, pace, angle, elev, vo2calc, t_tot, t_ex, fico2, fio2, feco2, feo2, vde, vco2, vo2, bf, ve, petco2, peto2, vo2kg, re, hr, la, rer, ve_stpd, veo2, veco2, tv, ee_ae, la_vo2, o2pulse, vde_tv, va, o2sa, rpe, bp_sys, bp_dia, own1, own2, own3, own4, own5, step_is_rest, step_is_30max, step_is_60max, step_is_rec, calc_start, calc_end, comments, timestart, duration, eco, p, wkg, vo2_30s, vo2_pr, step_is_last, deleted, created_by, mod_by, mod_date, created_date, modded, own6, own7, own8, own9, own10, to2, tco2
FROM dirteststeps
WHERE idmeasurement = ANY($1::int[])
ORDER BY idmeasurement, stepno
`

func (q *Queries) GetDirTestStepsByMeasurementIDs(ctx context.Context, dollar_1 []int32) ([]Dirteststep, error) {
	rows, err := q.query(ctx, q.getDirTestStepsByMeasurementIDsStmt, getDirTestStepsByMeasurementIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dirteststep
	for rows.Next() {
		var i Dirteststep
		if err := rows.Scan(
			&i.Iddirteststeps,
			&i.Idmeasurement,
			&i.Stepno,
			&i.AnaTime,
			&i.Timestop,
			&i.Speed,
			&i.Pace,
			&i.Angle,
			&i.Elev,
			&i.Vo2calc,
			&i.TTot,
			&i.TEx,
			&i.Fico2,
			&i.Fio2,
			&i.Feco2,
			&i.Feo2,
			&i.Vde,
			&i.Vco2,
			&i.Vo2,
			&i.Bf,
			&i.Ve,
			&i.Petco2,
			&i.Peto2,
			&i.Vo2kg,
			&i.Re,
			&i.Hr,
			&i.La,
			&i.Rer,
			&i.VeStpd,
			&i.Veo2,
			&i.Veco2,
			&i.Tv,
			&i.EeAe,
			&i.LaVo2,
			&i.O2pulse,
			&i.VdeTv,
			&i.Va,
			&i.O2sa,
			&i.Rpe,
			&i.BpSys,
			&i.BpDia,
			&i.Own1,
			&i.Own2,
			&i.Own3,
			&i.Own4,
			&i.Own5,
			&i.StepIsRest,
			&i.StepIs30max,
			&i.StepIs60max,
			&i.StepIsRec,
			&i.CalcStart,
			&i.CalcEnd,
			&i.Comments,
			&i.Timestart,
			&i.Duration,
			&i.Eco,
			&i.P,
			&i.Wkg,
			&i.Vo230s,
			&i.Vo2Pr,
			&i.StepIsLast,
			&i.Deleted,
			&i.CreatedBy,
			&i.ModBy,
			&i.ModDate,
			&i.CreatedDate,
			&i.Modded,
			&i.Own6,
			&i.Own7,
			&i.Own8,
			&i.Own9,
			&i.Own10,
			&i.To2,
			&i.Tco2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirTestsByMeasurementIDs = `-- name: GetDirTestsByMeasurementIDs :many
SELECT iddirtest, idmeasurement, meascols, weightkg, heightcm, bmi, fat_pr, fat_p1, fat_p2, fat_p3, fat_p4, fat_style, fat_equip, fvc, fev1, air_press, air_temp, air_humid, testprotocol, air_press_unit, settingslist, lt1_x, lt1_y, lt2_x, lt2_y, vt1_x, vt2_x, vt1_y, vt2_y, lt1_calc_x, lt1_calc_y, lt2_calc_x, lt2_calc_y, protocolmodel, testtype, protocolxval, steptime, w_rest, created_by, mod_by, mod_date, deleted, created_date, modded, norawdata
FROM dirtest
WHERE idmeasurement = ANY($1::int[])
ORDER BY idmeasurement
`

func (q *Queries) GetDirTestsByMeasurementIDs(ctx context.Context, dollar_1 []int32) ([]Dirtest, error) {
	rows, err := q.query(ctx, q.getDirTestsByMeasurementIDsStmt, getDirTestsByMeasurementIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dirtest
	for rows.Next() {
		var i Dirtest
		if err := rows.Scan(
			&i.Iddirtest,
			&i.Idmeasurement,
			&i.Meascols,
			&i.Weightkg,
			&i.Heightcm,
			&i.Bmi,
			&i.FatPr,
			&i.FatP1,
			&i.FatP2,
			&i.FatP3,
			&i.FatP4,
			&i.FatStyle,
			&i.FatEquip,
			&i.Fvc,
			&i.Fev1,
			&i.AirPress,
			&i.AirTemp,
			&i.AirHumid,
			&i.Testprotocol,
			&i.AirPressUnit,
			&i.Settingslist,
			&i.Lt1X,
			&i.Lt1Y,
			&i.Lt2X,
			&i.Lt2Y,
			&i.Vt1X,
			&i.Vt2X,
			&i.Vt1Y,
			&i.Vt2Y,
			&i.Lt1CalcX,
			&i.Lt1CalcY,
			&i.Lt2CalcX,
			&i.Lt2CalcY,
			&i.Protocolmodel,
			&i.Testtype,
			&i.Protocolxval,
			&i.Steptime,
			&i.WRest,
			&i.CreatedBy,
			&i.ModBy,
			&i.ModDate,
			&i.Deleted,
			&i.CreatedDate,
			&i.Modded,
			&i.Norawdata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurementsByCustomer = `-- name: GetMeasurementsByCustomer :many
SELECT idmeasurement, measname, idcustomer, tablename, idpatterndef, do_year, do_month, do_day, do_hour, do_min, sessionno, info, measurements, groupnotes, cbcharts, cbcomments, created_by, mod_by, mod_date, deleted, created_date, modded, test_location, keywords, tester_name, modder_name, meastype, sent_to_sprintai
FROM measurement_list
WHERE idcustomer = $1
ORDER BY idmeasurement
`

func (q *Queries) GetMeasurementsByCustomer(ctx context.Context, idcustomer int32) ([]MeasurementList, error) {
	rows, err := q.query(ctx, q.getMeasurementsByCustomerStmt, getMeasurementsByCustomer, idcustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeasurementList
	for rows.Next() {
		var i MeasurementList
		if err := rows.Scan(
			&i.Idmeasurement,
			&i.Measname,
			&i.Idcustomer,
			&i.Tablename,
			&i.Idpatterndef,
			&i.DoYear,
			&i.DoMonth,
			&i.DoDay,
			&i.DoHour,
			&i.DoMin,
			&i.Sessionno,
			&i.Info,
			&i.Measurements,
			&i.Groupnotes,
			&i.Cbcharts,
			&i.Cbcomments,
			&i.CreatedBy,
			&i.ModBy,
			&i.ModDate,
			&i.Deleted,
			&i.CreatedDate,
			&i.Modded,
			&i.TestLocation,
			&i.Keywords,
			&i.TesterName,
			&i.ModderName,
			&i.Meastype,
			&i.SentToSprintai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDirRawData = `-- name: InsertDirRawData :exec
INSERT INTO dirrawdata (
    iddirrawdata, idmeasurement, rawdata, columndata, info, unitsdata,
    created_by, mod_by, mod_date, deleted, created_date, modded
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
ON CONFLICT (iddirrawdata) DO UPDATE SET
    idmeasurement = EXCLUDED.idmeasurement,
    rawdata = EXCLUDED.rawdata,
    columndata = EXCLUDED.columndata,
    info = EXCLUDED.info,
    unitsdata = EXCLUDED.unitsdata,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    deleted = EXCLUDED.deleted,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded
`

type InsertDirRawDataParams struct {
	Iddirrawdata  int32
	Idmeasurement int32
	Rawdata       sql.NullString
	Columndata    sql.NullString
	Info          sql.NullString
	Unitsdata     sql.NullString
	CreatedBy     sql.NullInt64
	ModBy         sql.NullInt64
	ModDate       sql.NullTime
	Deleted       sql.NullInt16
	CreatedDate   sql.NullTime
	Modded        sql.NullInt16
}

func (q *Queries) InsertDirRawData(ctx context.Context, arg InsertDirRawDataParams) error {
	_, err := q.exec(ctx, q.insertDirRawDataStmt, insertDirRawData,
		arg.Iddirrawdata,
		arg.Idmeasurement,
		arg.Rawdata,
		arg.Columndata,
		arg.Info,
		arg.Unitsdata,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.Deleted,
		arg.CreatedDate,
		arg.Modded,
	)
	return err
}

const insertDirReport = `-- name: InsertDirReport :exec
INSERT INTO dirreport (
    iddirreport, page_instructions, idmeasurement, template_rec, librec_name,
    created_by, mod_by, mod_date, deleted, created_date, modded
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
ON CONFLICT (iddirreport) DO UPDATE SET
    page_instructions = EXCLUDED.page_instructions,
    idmeasurement = EXCLUDED.idmeasurement,
    template_rec = EXCLUDED.template_rec,
    librec_name = EXCLUDED.librec_name,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    deleted = EXCLUDED.deleted,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded
`

type InsertDirReportParams struct {
	Iddirreport      int32
	PageInstructions sql.NullString
	Idmeasurement    int32
	TemplateRec      sql.NullInt32
	LibrecName       sql.NullString
	CreatedBy        sql.NullInt64
	ModBy            sql.NullInt64
	ModDate          sql.NullTime
	Deleted          sql.NullInt16
	CreatedDate      sql.NullTime
	Modded           sql.NullInt16
}

func (q *Queries) InsertDirReport(ctx context.Context, arg InsertDirReportParams) error {
	_, err := q.exec(ctx, q.insertDirReportStmt, insertDirReport,
		arg.Iddirreport,
		arg.PageInstructions,
		arg.Idmeasurement,
		arg.TemplateRec,
		arg.LibrecName,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.Deleted,
		arg.CreatedDate,
		arg.Modded,
	)
	return err
}

const insertDirResults = `-- name: InsertDirResults :exec
INSERT INTO dirresults (
    iddirresults, idmeasurement, max_vo2mlkgmin, max_vo2mlmin, max_vo2,
    max_hr, max_speed, max_pace, max_p, max_pkg, max_angle, max_lac,
    max_add1, max_add2, max_add3,
    lac_ank_vo2mlkgmin, lac_ank_vo2mlmin, lac_ank_vo2, lac_ank_vo2pr,
    lac_ank_hr, lac_ank_speed, lac_ank_pace, lac_ank_p, lac_ank_pkg,
    lac_ank_angle, lac_ank_lac, lac_ank_add1, lac_ank_add2, lac_ank_add3,
    lac_aerk_vo2mlkgmin, lac_aerk_vo2mlmin, lac_aerk_vo2, lac_aerk_vo2pr,
    lac_aerk_hr, lac_aerk_speed, lac_aerk_pace, lac_aerk_p, lac_aerk_pkg,
    lac_aerk_angle, lac_aerk_lac, lac_aerk_add1, lac_aerk_add2, lac_aerk_add3,
    vent_ank_vo2mlkgmin, vent_ank_vo2mlmin, vent_ank_vo2, vent_ank_vo2pr,
    vent_ank_hr, vent_ank_speed, vent_ank_pace, vent_ank_p, vent_ank_pkg,
    vent_ank_angle, vent_ank_lac, vent_ank_add1, vent_ank_add2, vent_ank_add3,
    vent_aerk_vo2mlkgmin, vent_aerk_vo2mlmin, vent_aerk_vo2, vent_aerk_vo2pr,
    vent_aerk_hr, vent_aerk_speed, vent_aerk_pace, vent_aerk_p, vent_aerk_pkg,
    vent_aerk_angle, vent_aerk_lac, vent_aerk_add1, vent_aerk_add2, vent_aerk_add3,
    created_by, mod_by, mod_date, deleted, created_date, modded
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18, $19,
    $20, $21, $22, $23, $24,
    $25, $26, $27, $28, $29,
    $30, $31, $32, $33,
    $34, $35, $36, $37, $38,
    $39, $40, $41, $42, $43,
    $44, $45, $46, $47,
    $48, $49, $50, $51, $52,
    $53, $54, $55, $56, $57,
    $58, $59, $60,
    $61, $62, $63, $64, $65, $66,
    $67, $68, $69, $70, $71, $72,
    $73, $74, $75,
    $76, $77
)
ON CONFLICT (iddirresults) DO UPDATE SET
    idmeasurement = EXCLUDED.idmeasurement,
    max_vo2mlkgmin = EXCLUDED.max_vo2mlkgmin,
    max_vo2mlmin = EXCLUDED.max_vo2mlmin,
    max_vo2 = EXCLUDED.max_vo2,
    max_hr = EXCLUDED.max_hr,
    max_speed = EXCLUDED.max_speed,
    max_pace = EXCLUDED.max_pace,
    max_p = EXCLUDED.max_p,
    max_pkg = EXCLUDED.max_pkg,
    max_angle = EXCLUDED.max_angle,
    max_lac = EXCLUDED.max_lac,
    max_add1 = EXCLUDED.max_add1,
    max_add2 = EXCLUDED.max_add2,
    max_add3 = EXCLUDED.max_add3,
    lac_ank_vo2mlkgmin = EXCLUDED.lac_ank_vo2mlkgmin,
    lac_ank_vo2mlmin = EXCLUDED.lac_ank_vo2mlmin,
    lac_ank_vo2 = EXCLUDED.lac_ank_vo2,
    lac_ank_vo2pr = EXCLUDED.lac_ank_vo2pr,
    lac_ank_hr = EXCLUDED.lac_ank_hr,
    lac_ank_speed = EXCLUDED.lac_ank_speed,
    lac_ank_pace = EXCLUDED.lac_ank_pace,
    lac_ank_p = EXCLUDED.lac_ank_p,
    lac_ank_pkg = EXCLUDED.lac_ank_pkg,
    lac_ank_angle = EXCLUDED.lac_ank_angle,
    lac_ank_lac = EXCLUDED.lac_ank_lac,
    lac_ank_add1 = EXCLUDED.lac_ank_add1,
    lac_ank_add2 = EXCLUDED.lac_ank_add2,
    lac_ank_add3 = EXCLUDED.lac_ank_add3,
    lac_aerk_vo2mlkgmin = EXCLUDED.lac_aerk_vo2mlkgmin,
    lac_aerk_vo2mlmin = EXCLUDED.lac_aerk_vo2mlmin,
    lac_aerk_vo2 = EXCLUDED.lac_aerk_vo2,
    lac_aerk_vo2pr = EXCLUDED.lac_aerk_vo2pr,
    lac_aerk_hr = EXCLUDED.lac_aerk_hr,
    lac_aerk_speed = EXCLUDED.lac_aerk_speed,
    lac_aerk_pace = EXCLUDED.lac_aerk_pace,
    lac_aerk_p = EXCLUDED.lac_aerk_p,
    lac_aerk_pkg = EXCLUDED.lac_aerk_pkg,
    lac_aerk_angle = EXCLUDED.lac_aerk_angle,
    lac_aerk_lac = EXCLUDED.lac_aerk_lac,
    lac_aerk_add1 = EXCLUDED.lac_aerk_add1,
    lac_aerk_add2 = EXCLUDED.lac_aerk_add2,
    lac_aerk_add3 = EXCLUDED.lac_aerk_add3,
    vent_ank_vo2mlkgmin = EXCLUDED.vent_ank_vo2mlkgmin,
    vent_ank_vo2mlmin = EXCLUDED.vent_ank_vo2mlmin,
    vent_ank_vo2 = EXCLUDED.vent_ank_vo2,
    vent_ank_vo2pr = EXCLUDED.vent_ank_vo2pr,
    vent_ank_hr = EXCLUDED.vent_ank_hr,
    vent_ank_speed = EXCLUDED.vent_ank_speed,
    vent_ank_pace = EXCLUDED.vent_ank_pace,
    vent_ank_p = EXCLUDED.vent_ank_p,
    vent_ank_pkg = EXCLUDED.vent_ank_pkg,
    vent_ank_angle = EXCLUDED.vent_ank_angle,
    vent_ank_lac = EXCLUDED.vent_ank_lac,
    vent_ank_add1 = EXCLUDED.vent_ank_add1,
    vent_ank_add2 = EXCLUDED.vent_ank_add2,
    vent_ank_add3 = EXCLUDED.vent_ank_add3,
    vent_aerk_vo2mlkgmin = EXCLUDED.vent_aerk_vo2mlkgmin,
    vent_aerk_vo2mlmin = EXCLUDED.vent_aerk_vo2mlmin,
    vent_aerk_vo2 = EXCLUDED.vent_aerk_vo2,
    vent_aerk_vo2pr = EXCLUDED.vent_aerk_vo2pr,
    vent_aerk_hr = EXCLUDED.vent_aerk_hr,
    vent_aerk_speed = EXCLUDED.vent_aerk_speed,
    vent_aerk_pace = EXCLUDED.vent_aerk_pace,
    vent_aerk_p = EXCLUDED.vent_aerk_p,
    vent_aerk_pkg = EXCLUDED.vent_aerk_pkg,
    vent_aerk_angle = EXCLUDED.vent_aerk_angle,
    vent_aerk_lac = EXCLUDED.vent_aerk_lac,
    vent_aerk_add1 = EXCLUDED.vent_aerk_add1,
    vent_aerk_add2 = EXCLUDED.vent_aerk_add2,
    vent_aerk_add3 = EXCLUDED.vent_aerk_add3,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    deleted = EXCLUDED.deleted,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded
`

type InsertDirResultsParams struct {
	Iddirresults       int32
	Idmeasurement      int32
	MaxVo2mlkgmin      sql.NullFloat64
	MaxVo2mlmin        sql.NullFloat64
	MaxVo2             sql.NullFloat64
	MaxHr              sql.NullFloat64
	MaxSpeed           sql.NullFloat64
	MaxPace            sql.NullFloat64
	MaxP               sql.NullFloat64
	MaxPkg             sql.NullFloat64
	MaxAngle           sql.NullFloat64
	MaxLac             sql.NullFloat64
	MaxAdd1            sql.NullFloat64
	MaxAdd2            sql.NullFloat64
	MaxAdd3            sql.NullFloat64
	LacAnkVo2mlkgmin   sql.NullFloat64
	LacAnkVo2mlmin     sql.NullFloat64
	LacAnkVo2          sql.NullFloat64
	LacAnkVo2pr        sql.NullFloat64
	LacAnkHr           sql.NullFloat64
	LacAnkSpeed        sql.NullFloat64
	LacAnkPace         sql.NullFloat64
	LacAnkP            sql.NullFloat64
	LacAnkPkg          sql.NullFloat64
	LacAnkAngle        sql.NullFloat64
	LacAnkLac          sql.NullFloat64
	LacAnkAdd1         sql.NullFloat64
	LacAnkAdd2         sql.NullFloat64
	LacAnkAdd3         sql.NullFloat64
	LacAerkVo2mlkgmin  sql.NullFloat64
	LacAerkVo2mlmin    sql.NullFloat64
	LacAerkVo2         sql.NullFloat64
	LacAerkVo2pr       sql.NullFloat64
	LacAerkHr          sql.NullFloat64
	LacAerkSpeed       sql.NullFloat64
	LacAerkPace        sql.NullFloat64
	LacAerkP           sql.NullFloat64
	LacAerkPkg         sql.NullFloat64
	LacAerkAngle       sql.NullFloat64
	LacAerkLac         sql.NullFloat64
	LacAerkAdd1        sql.NullFloat64
	LacAerkAdd2        sql.NullFloat64
	LacAerkAdd3        sql.NullFloat64
	VentAnkVo2mlkgmin  sql.NullFloat64
	VentAnkVo2mlmin    sql.NullFloat64
	VentAnkVo2         sql.NullFloat64
	VentAnkVo2pr       sql.NullFloat64
	VentAnkHr          sql.NullFloat64
	VentAnkSpeed       sql.NullFloat64
	VentAnkPace        sql.NullFloat64
	VentAnkP           sql.NullFloat64
	VentAnkPkg         sql.NullFloat64
	VentAnkAngle       sql.NullFloat64
	VentAnkLac         sql.NullFloat64
	VentAnkAdd1        sql.NullFloat64
	VentAnkAdd2        sql.NullFloat64
	VentAnkAdd3        sql.NullFloat64
	VentAerkVo2mlkgmin sql.NullFloat64
	VentAerkVo2mlmin   sql.NullFloat64
	VentAerkVo2        sql.NullFloat64
	VentAerkVo2pr      sql.NullFloat64
	VentAerkHr         sql.NullFloat64
	VentAerkSpeed      sql.NullFloat64
	VentAerkPace       sql.NullFloat64
	VentAerkP          sql.NullFloat64
	VentAerkPkg        sql.NullFloat64
	VentAerkAngle      sql.NullFloat64
	VentAerkLac        sql.NullFloat64
	VentAerkAdd1       sql.NullFloat64
	VentAerkAdd2       sql.NullFloat64
	VentAerkAdd3       sql.NullFloat64
	CreatedBy          sql.NullInt64
	ModBy              sql.NullInt64
	ModDate            sql.NullTime
	Deleted            sql.NullInt16
	CreatedDate        sql.NullTime
	Modded             sql.NullInt16
}

func (q *Queries) InsertDirResults(ctx context.Context, arg InsertDirResultsParams) error {
	_, err := q.exec(ctx, q.insertDirResultsStmt, insertDirResults,
		arg.Iddirresults,
		arg.Idmeasurement,
		arg.MaxVo2mlkgmin,
		arg.MaxVo2mlmin,
		arg.MaxVo2,
		arg.MaxHr,
		arg.MaxSpeed,
		arg.MaxPace,
		arg.MaxP,
		arg.MaxPkg,
		arg.MaxAngle,
		arg.MaxLac,
		arg.MaxAdd1,
		arg.MaxAdd2,
		arg.MaxAdd3,
		arg.LacAnkVo2mlkgmin,
		arg.LacAnkVo2mlmin,
		arg.LacAnkVo2,
		arg.LacAnkVo2pr,
		arg.LacAnkHr,
		arg.LacAnkSpeed,
		arg.LacAnkPace,
		arg.LacAnkP,
		arg.LacAnkPkg,
		arg.LacAnkAngle,
		arg.LacAnkLac,
		arg.LacAnkAdd1,
		arg.LacAnkAdd2,
		arg.LacAnkAdd3,
		arg.LacAerkVo2mlkgmin,
		arg.LacAerkVo2mlmin,
		arg.LacAerkVo2,
		arg.LacAerkVo2pr,
		arg.LacAerkHr,
		arg.LacAerkSpeed,
		arg.LacAerkPace,
		arg.LacAerkP,
		arg.LacAerkPkg,
		arg.LacAerkAngle,
		arg.LacAerkLac,
		arg.LacAerkAdd1,
		arg.LacAerkAdd2,
		arg.LacAerkAdd3,
		arg.VentAnkVo2mlkgmin,
		arg.VentAnkVo2mlmin,
		arg.VentAnkVo2,
		arg.VentAnkVo2pr,
		arg.VentAnkHr,
		arg.VentAnkSpeed,
		arg.VentAnkPace,
		arg.VentAnkP,
		arg.VentAnkPkg,
		arg.VentAnkAngle,
		arg.VentAnkLac,
		arg.VentAnkAdd1,
		arg.VentAnkAdd2,
		arg.VentAnkAdd3,
		arg.VentAerkVo2mlkgmin,
		arg.VentAerkVo2mlmin,
		arg.VentAerkVo2,
		arg.VentAerkVo2pr,
		arg.VentAerkHr,
		arg.VentAerkSpeed,
		arg.VentAerkPace,
		arg.VentAerkP,
		arg.VentAerkPkg,
		arg.VentAerkAngle,
		arg.VentAerkLac,
		arg.VentAerkAdd1,
		arg.VentAerkAdd2,
		arg.VentAerkAdd3,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.Deleted,
		arg.CreatedDate,
		arg.Modded,
	)
	return err
}

const insertDirTest = `-- name: InsertDirTest :exec
INSERT INTO dirtest (
    iddirtest, idmeasurement, meascols, weightkg, heightcm, bmi,
    fat_pr, fat_p1, fat_p2, fat_p3, fat_p4, fat_style, fat_equip,
    fvc, fev1, air_press, air_temp, air_humid, testprotocol, air_press_unit,
    settingslist, lt1_x, lt1_y, lt2_x, lt2_y, vt1_x, vt2_x, vt1_y, vt2_y,
    lt1_calc_x, lt1_calc_y, lt2_calc_x, lt2_calc_y, protocolmodel, testtype,
    protocolxval, steptime, w_rest, created_by, mod_by, mod_date, deleted,
    created_date, modded, norawdata
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29,
    $30, $31, $32, $33, $34, $35,
    $36, $37, $38, $39, $40, $41, $42,
    $43, $44, $45
)
ON CONFLICT (iddirtest) DO UPDATE SET
    idmeasurement = EXCLUDED.idmeasurement,
    meascols = EXCLUDED.meascols,
    weightkg = EXCLUDED.weightkg,
    heightcm = EXCLUDED.heightcm,
    bmi = EXCLUDED.bmi,
    fat_pr = EXCLUDED.fat_pr,
    fat_p1 = EXCLUDED.fat_p1,
    fat_p2 = EXCLUDED.fat_p2,
    fat_p3 = EXCLUDED.fat_p3,
    fat_p4 = EXCLUDED.fat_p4,
    fat_style = EXCLUDED.fat_style,
    fat_equip = EXCLUDED.fat_equip,
    fvc = EXCLUDED.fvc,
    fev1 = EXCLUDED.fev1,
    air_press = EXCLUDED.air_press,
    air_temp = EXCLUDED.air_temp,
    air_humid = EXCLUDED.air_humid,
    testprotocol = EXCLUDED.testprotocol,
    air_press_unit = EXCLUDED.air_press_unit,
    settingslist = EXCLUDED.settingslist,
    lt1_x = EXCLUDED.lt1_x,
    lt1_y = EXCLUDED.lt1_y,
    lt2_x = EXCLUDED.lt2_x,
    lt2_y = EXCLUDED.lt2_y,
    vt1_x = EXCLUDED.vt1_x,
    vt2_x = EXCLUDED.vt2_x,
    vt1_y = EXCLUDED.vt1_y,
    vt2_y = EXCLUDED.vt2_y,
    lt1_calc_x = EXCLUDED.lt1_calc_x,
    lt1_calc_y = EXCLUDED.lt1_calc_y,
    lt2_calc_x = EXCLUDED.lt2_calc_x,
    lt2_calc_y = EXCLUDED.lt2_calc_y,
    protocolmodel = EXCLUDED.protocolmodel,
    testtype = EXCLUDED.testtype,
    protocolxval = EXCLUDED.protocolxval,
    steptime = EXCLUDED.steptime,
    w_rest = EXCLUDED.w_rest,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    deleted = EXCLUDED.deleted,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded,
    norawdata = EXCLUDED.norawdata
`

type InsertDirTestParams struct {
	Iddirtest     int32
	Idmeasurement int32
	Meascols      sql.NullString
	Weightkg      sql.NullFloat64
	Heightcm      sql.NullFloat64
	Bmi           sql.NullFloat64
	FatPr         sql.NullFloat64
	FatP1         sql.NullFloat64
	FatP2         sql.NullFloat64
	FatP3         sql.NullFloat64
	FatP4         sql.NullFloat64
	FatStyle      sql.NullInt32
	FatEquip      sql.NullString
	Fvc           sql.NullFloat64
	Fev1          sql.NullFloat64
	AirPress      sql.NullFloat64
	AirTemp       sql.NullFloat64
	AirHumid      sql.NullFloat64
	Testprotocol  sql.NullString
	AirPressUnit  sql.NullInt32
	Settingslist  sql.NullString
	Lt1X          sql.NullFloat64
	Lt1Y          sql.NullFloat64
	Lt2X          sql.NullFloat64
	Lt2Y          sql.NullFloat64
	Vt1X          sql.NullFloat64
	Vt2X          sql.NullFloat64
	Vt1Y          sql.NullFloat64
	Vt2Y          sql.NullFloat64
	Lt1CalcX      sql.NullFloat64
	Lt1CalcY      sql.NullFloat64
	Lt2CalcX      sql.NullFloat64
	Lt2CalcY      sql.NullFloat64
	Protocolmodel sql.NullInt16
	Testtype      sql.NullInt16
	Protocolxval  sql.NullInt16
	Steptime      sql.NullInt32
	WRest         sql.NullInt16
	CreatedBy     sql.NullInt64
	ModBy         sql.NullInt64
	ModDate       sql.NullTime
	Deleted       sql.NullInt16
	CreatedDate   sql.NullTime
	Modded        sql.NullInt16
	Norawdata     sql.NullInt16
}

func (q *Queries) InsertDirTest(ctx context.Context, arg InsertDirTestParams) error {
	_, err := q.exec(ctx, q.insertDirTestStmt, insertDirTest,
		arg.Iddirtest,
		arg.Idmeasurement,
		arg.Meascols,
		arg.Weightkg,
		arg.Heightcm,
		arg.Bmi,
		arg.FatPr,
		arg.FatP1,
		arg.FatP2,
		arg.FatP3,
		arg.FatP4,
		arg.FatStyle,
		arg.FatEquip,
		arg.Fvc,
		arg.Fev1,
		arg.AirPress,
		arg.AirTemp,
		arg.AirHumid,
		arg.Testprotocol,
		arg.AirPressUnit,
		arg.Settingslist,
		arg.Lt1X,
		arg.Lt1Y,
		arg.Lt2X,
		arg.Lt2Y,
		arg.Vt1X,
		arg.Vt2X,
		arg.Vt1Y,
		arg.Vt2Y,
		arg.Lt1CalcX,
		arg.Lt1CalcY,
		arg.Lt2CalcX,
		arg.Lt2CalcY,
		arg.Protocolmodel,
		arg.Testtype,
		arg.Protocolxval,
		arg.Steptime,
		arg.WRest,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.Deleted,
		arg.CreatedDate,
		arg.Modded,
		arg.Norawdata,
	)
	return err
}

const insertDirTestStep = `-- name: InsertDirTestStep :exec
INSERT INTO dirteststeps (
    iddirteststeps, idmeasurement, stepno, ana_time, timestop, speed, pace,
    angle, elev, vo2calc, t_tot, t_ex, fico2, fio2, feco2, feo2, vde, vco2,
    vo2, bf, ve, petco2, peto2, vo2kg, re, hr, la, rer, ve_stpd, veo2,
    veco2, tv, ee_ae, la_vo2, o2pulse, vde_tv, va, o2sa, rpe,
    bp_sys, bp_dia, own1, own2, own3, own4, own5,
    step_is_rest, step_is_30max, step_is_60max, step_is_rec, calc_start,
    calc_end, comments, timestart, duration, eco, p, wkg,
    vo2_30s, vo2_pr, step_is_last, deleted, created_by,
    mod_by, mod_date, created_date, modded, own6, own7, own8, own9, own10,
    to2, tco2
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29,
    $30, $31, $32, $33, $34, $35, $36, $37, $38, $39,
    $40, $41, $42, $43, $44, $45, $46,
    $47, $48, $49, $50, $51,
    $52, $53, $54, $55, $56, $57, $58,
    $59, $60, $61, $62, $63,
    $64, $65, $66, $67, $68, $69, $70, $71, $72,
    $73, $74
)
ON CONFLICT (iddirteststeps) DO UPDATE SET
    idmeasurement = EXCLUDED.idmeasurement,
    stepno = EXCLUDED.stepno,
    ana_time = EXCLUDED.ana_time,
    timestop = EXCLUDED.timestop,
    speed = EXCLUDED.speed,
    pace = EXCLUDED.pace,
    angle = EXCLUDED.angle,
    elev = EXCLUDED.elev,
    vo2calc = EXCLUDED.vo2calc,
    t_tot = EXCLUDED.t_tot,
    t_ex = EXCLUDED.t_ex,
    fico2 = EXCLUDED.fico2,
    fio2 = EXCLUDED.fio2,
    feco2 = EXCLUDED.feco2,
    feo2 = EXCLUDED.feo2,
    vde = EXCLUDED.vde,
    vco2 = EXCLUDED.vco2,
    vo2 = EXCLUDED.vo2,
    bf = EXCLUDED.bf,
    ve = EXCLUDED.ve,
    petco2 = EXCLUDED.petco2,
    peto2 = EXCLUDED.peto2,
    vo2kg = EXCLUDED.vo2kg,
    re = EXCLUDED.re,
    hr = EXCLUDED.hr,
    la = EXCLUDED.la,
    rer = EXCLUDED.rer,
    ve_stpd = EXCLUDED.ve_stpd,
    veo2 = EXCLUDED.veo2,
    veco2 = EXCLUDED.veco2,
    tv = EXCLUDED.tv,
    ee_ae = EXCLUDED.ee_ae,
    la_vo2 = EXCLUDED.la_vo2,
    o2pulse = EXCLUDED.o2pulse,
    vde_tv = EXCLUDED.vde_tv,
    va = EXCLUDED.va,
    o2sa = EXCLUDED.o2sa,
    rpe = EXCLUDED.rpe,
    bp_sys = EXCLUDED.bp_sys,
    bp_dia = EXCLUDED.bp_dia,
    own1 = EXCLUDED.own1,
    own2 = EXCLUDED.own2,
    own3 = EXCLUDED.own3,
    own4 = EXCLUDED.own4,
    own5 = EXCLUDED.own5,
    step_is_rest = EXCLUDED.step_is_rest,
    step_is_30max = EXCLUDED.step_is_30max,
    step_is_60max = EXCLUDED.step_is_60max,
    step_is_rec = EXCLUDED.step_is_rec,
    calc_start = EXCLUDED.calc_start,
    calc_end = EXCLUDED.calc_end,
    comments = EXCLUDED.comments,
    timestart = EXCLUDED.timestart,
    duration = EXCLUDED.duration,
    eco = EXCLUDED.eco,
    p = EXCLUDED.p,
    wkg = EXCLUDED.wkg,
    vo2_30s = EXCLUDED.vo2_30s,
    vo2_pr = EXCLUDED.vo2_pr,
    step_is_last = EXCLUDED.step_is_last,
    deleted = EXCLUDED.deleted,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded,
    own6 = EXCLUDED.own6,
    own7 = EXCLUDED.own7,
    own8 = EXCLUDED.own8,
    own9 = EXCLUDED.own9,
    own10 = EXCLUDED.own10,
    to2 = EXCLUDED.to2,
    tco2 = EXCLUDED.tco2
`

type InsertDirTestStepParams struct {
	Iddirteststeps int32
	Idmeasurement  int32
	Stepno         sql.NullInt32
	AnaTime        sql.NullInt32
	Timestop       sql.NullFloat64
	Speed          sql.NullFloat64
	Pace           sql.NullFloat64
	Angle          sql.NullFloat64
	Elev           sql.NullFloat64
	Vo2calc        sql.NullFloat64
	TTot           sql.NullFloat64
	TEx            sql.NullFloat64
	Fico2          sql.NullFloat64
	Fio2           sql.NullFloat64
	Feco2          sql.NullFloat64
	Feo2           sql.NullFloat64
	Vde            sql.NullFloat64
	Vco2           sql.NullFloat64
	Vo2            sql.NullFloat64
	Bf             sql.NullFloat64
	Ve             sql.NullFloat64
	Petco2         sql.NullFloat64
	Peto2          sql.NullFloat64
	Vo2kg          sql.NullFloat64
	Re             sql.NullFloat64
	Hr             sql.NullFloat64
	La             sql.NullFloat64
	Rer            sql.NullFloat64
	VeStpd         sql.NullFloat64
	Veo2           sql.NullFloat64
	Veco2          sql.NullFloat64
	Tv             sql.NullFloat64
	EeAe           sql.NullFloat64
	LaVo2          sql.NullFloat64
	O2pulse        sql.NullFloat64
	VdeTv          sql.NullFloat64
	Va             sql.NullFloat64
	O2sa           sql.NullFloat64
	Rpe            sql.NullFloat64
	BpSys          sql.NullFloat64
	BpDia          sql.NullFloat64
	Own1           sql.NullFloat64
	Own2           sql.NullFloat64
	Own3           sql.NullFloat64
	Own4           sql.NullFloat64
	Own5           sql.NullFloat64
	StepIsRest     sql.NullInt32
	StepIs30max    sql.NullInt32
	StepIs60max    sql.NullInt32
	StepIsRec      sql.NullInt32
	CalcStart      sql.NullInt32
	CalcEnd        sql.NullInt32
	Comments       sql.NullString
	Timestart      sql.NullFloat64
	Duration       sql.NullFloat64
	Eco            sql.NullFloat64
	P              sql.NullFloat64
	Wkg            sql.NullFloat64
	Vo230s         sql.NullFloat64
	Vo2Pr          sql.NullFloat64
	StepIsLast     sql.NullInt32
	Deleted        sql.NullInt16
	CreatedBy      sql.NullInt64
	ModBy          sql.NullInt64
	ModDate        sql.NullTime
	CreatedDate    sql.NullTime
	Modded         sql.NullInt16
	Own6           sql.NullFloat64
	Own7           sql.NullFloat64
	Own8           sql.NullFloat64
	Own9           sql.NullFloat64
	Own10          sql.NullFloat64
	To2            sql.NullFloat64
	Tco2           sql.NullFloat64
}

func (q *Queries) InsertDirTestStep(ctx context.Context, arg InsertDirTestStepParams) error {
	_, err := q.exec(ctx, q.insertDirTestStepStmt, insertDirTestStep,
		arg.Iddirteststeps,
		arg.Idmeasurement,
		arg.Stepno,
		arg.AnaTime,
		arg.Timestop,
		arg.Speed,
		arg.Pace,
		arg.Angle,
		arg.Elev,
		arg.Vo2calc,
		arg.TTot,
		arg.TEx,
		arg.Fico2,
		arg.Fio2,
		arg.Feco2,
		arg.Feo2,
		arg.Vde,
		arg.Vco2,
		arg.Vo2,
		arg.Bf,
		arg.Ve,
		arg.Petco2,
		arg.Peto2,
		arg.Vo2kg,
		arg.Re,
		arg.Hr,
		arg.La,
		arg.Rer,
		arg.VeStpd,
		arg.Veo2,
		arg.Veco2,
		arg.Tv,
		arg.EeAe,
		arg.LaVo2,
		arg.O2pulse,
		arg.VdeTv,
		arg.Va,
		arg.O2sa,
		arg.Rpe,
		arg.BpSys,
		arg.BpDia,
		arg.Own1,
		arg.Own2,
		arg.Own3,
		arg.Own4,
		arg.Own5,
		arg.StepIsRest,
		arg.StepIs30max,
		arg.StepIs60max,
		arg.StepIsRec,
		arg.CalcStart,
		arg.CalcEnd,
		arg.Comments,
		arg.Timestart,
		arg.Duration,
		arg.Eco,
		arg.P,
		arg.Wkg,
		arg.Vo230s,
		arg.Vo2Pr,
		arg.StepIsLast,
		arg.Deleted,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.CreatedDate,
		arg.Modded,
		arg.Own6,
		arg.Own7,
		arg.Own8,
		arg.Own9,
		arg.Own10,
		arg.To2,
		arg.Tco2,
	)
	return err
}

const insertMeasurement = `-- name: InsertMeasurement :exec
INSERT INTO measurement_list (
    idmeasurement, measname, idcustomer, tablename, idpatterndef,
    do_year, do_month, do_day, do_hour, do_min, sessionno, info,
    measurements, groupnotes, cbcharts, cbcomments,
    created_by, mod_by, mod_date, deleted, created_date, modded,
    test_location, keywords, tester_name, modder_name, meastype,
    sent_to_sprintai
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22,
    $23, $24, $25, $26, $27,
    $28
)
ON CONFLICT (idmeasurement) DO UPDATE SET
    measname = EXCLUDED.measname,
    idcustomer = EXCLUDED.idcustomer,
    tablename = EXCLUDED.tablename,
    idpatterndef = EXCLUDED.idpatterndef,
    do_year = EXCLUDED.do_year,
    do_month = EXCLUDED.do_month,
    do_day = EXCLUDED.do_day,
    do_hour = EXCLUDED.do_hour,
    do_min = EXCLUDED.do_min,
    sessionno = EXCLUDED.sessionno,
    info = EXCLUDED.info,
    measurements = EXCLUDED.measurements,
    groupnotes = EXCLUDED.groupnotes,
    cbcharts = EXCLUDED.cbcharts,
    cbcomments = EXCLUDED.cbcomments,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    deleted = EXCLUDED.deleted,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded,
    test_location = EXCLUDED.test_location,
    keywords = EXCLUDED.keywords,
    tester_name = EXCLUDED.tester_name,
    modder_name = EXCLUDED.modder_name,
    meastype = EXCLUDED.meastype,
    sent_to_sprintai = EXCLUDED.sent_to_sprintai
`

type InsertMeasurementParams struct {
	Idmeasurement  int32
	Measname       sql.NullString
	Idcustomer     int32
	Tablename      sql.NullString
	Idpatterndef   sql.NullString
	DoYear         sql.NullInt16
	DoMonth        sql.NullInt16
	DoDay          sql.NullInt16
	DoHour         sql.NullInt16
	DoMin          sql.NullInt16
	Sessionno      sql.NullInt32
	Info           sql.NullString
	Measurements   sql.NullString
	Groupnotes     sql.NullString
	Cbcharts       sql.NullString
	Cbcomments     sql.NullString
	CreatedBy      sql.NullInt64
	ModBy          sql.NullInt64
	ModDate        sql.NullTime
	Deleted        sql.NullInt16
	CreatedDate    sql.NullTime
	Modded         sql.NullInt16
	TestLocation   sql.NullString
	Keywords       sql.NullString
	TesterName     sql.NullString
	ModderName     sql.NullString
	Meastype       sql.NullInt32
	SentToSprintai sql.NullTime
}

func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error {
	_, err := q.exec(ctx, q.insertMeasurementStmt, insertMeasurement,
		arg.Idmeasurement,
		arg.Measname,
		arg.Idcustomer,
		arg.Tablename,
		arg.Idpatterndef,
		arg.DoYear,
		arg.DoMonth,
		arg.DoDay,
		arg.DoHour,
		arg.DoMin,
		arg.Sessionno,
		arg.Info,
		arg.Measurements,
		arg.Groupnotes,
		arg.Cbcharts,
		arg.Cbcomments,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.Deleted,
		arg.CreatedDate,
		arg.Modded,
		arg.TestLocation,
		arg.Keywords,
		arg.TesterName,
		arg.ModderName,
		arg.Meastype,
		arg.SentToSprintai,
	)
	return err
}

const upsertCustomer = `-- name: UpsertCustomer :exec
INSERT INTO customer (
    idcustomer, firstname, lastname, idgroups, dob, sex, dob_year, dob_month, dob_day,
    pid_number, company, occupation, education, address, phone_home, phone_work, phone_mobile,
    faxno, email, username, password, readonly, warnings, allow_to_save, allow_to_cloud, flag2,
    idsport, medication, addinfo, team_name, add1, athlete, add10, add20, updatemode, weight_kg,
    height_cm, date_modified, recom_testlevel, created_by, mod_by, mod_date, deleted,
    created_date, modded, allow_anonymous_data, locked, allow_to_sprintai, tosprintai_from,
    stat_sent, sportti_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, $25, $26,
    $27, $28, $29, $30, $31, $32, $33, $34, $35, $36,
    $37, $38, $39, $40, $41, $42, $43, $44,
    $45, $46, $47, $48, $49, $50, $51
)
ON CONFLICT (idcustomer) DO UPDATE SET
    firstname = EXCLUDED.firstname,
    lastname = EXCLUDED.lastname,
    idgroups = EXCLUDED.idgroups,
    dob = EXCLUDED.dob,
    sex = EXCLUDED.sex,
    dob_year = EXCLUDED.dob_year,
    dob_month = EXCLUDED.dob_month,
    dob_day = EXCLUDED.dob_day,
    pid_number = EXCLUDED.pid_number,
    company = EXCLUDED.company,
    occupation = EXCLUDED.occupation,
    education = EXCLUDED.education,
    address = EXCLUDED.address,
    phone_home = EXCLUDED.phone_home,
    phone_work = EXCLUDED.phone_work,
    phone_mobile = EXCLUDED.phone_mobile,
    faxno = EXCLUDED.faxno,
    email = EXCLUDED.email,
    username = EXCLUDED.username,
    password = EXCLUDED.password,
    readonly = EXCLUDED.readonly,
    warnings = EXCLUDED.warnings,
    allow_to_save = EXCLUDED.allow_to_save,
    allow_to_cloud = EXCLUDED.allow_to_cloud,
    flag2 = EXCLUDED.flag2,
    idsport = EXCLUDED.idsport,
    medication = EXCLUDED.medication,
    addinfo = EXCLUDED.addinfo,
    team_name = EXCLUDED.team_name,
    add1 = EXCLUDED.add1,
    athlete = EXCLUDED.athlete,
    add10 = EXCLUDED.add10,
    add20 = EXCLUDED.add20,
    updatemode = EXCLUDED.updatemode,
    weight_kg = EXCLUDED.weight_kg,
    height_cm = EXCLUDED.height_cm,
    date_modified = EXCLUDED.date_modified,
    recom_testlevel = EXCLUDED.recom_testlevel,
    created_by = EXCLUDED.created_by,
    mod_by = EXCLUDED.mod_by,
    mod_date = EXCLUDED.mod_date,
    deleted = EXCLUDED.deleted,
    created_date = EXCLUDED.created_date,
    modded = EXCLUDED.modded,
    allow_anonymous_data = EXCLUDED.allow_anonymous_data,
    locked = EXCLUDED.locked,
    allow_to_sprintai = EXCLUDED.allow_to_sprintai,
    tosprintai_from = EXCLUDED.tosprintai_from,
    stat_sent = EXCLUDED.stat_sent,
    sportti_id = EXCLUDED.sportti_id
`

type UpsertCustomerParams struct {
	Idcustomer         int32
	Firstname          string
	Lastname           string
	Idgroups           sql.NullInt32
	Dob                sql.NullTime
	Sex                sql.NullInt32
	DobYear            sql.NullInt32
	DobMonth           sql.NullInt32
	DobDay             sql.NullInt32
	PidNumber          sql.NullString
	Company            sql.NullString
	Occupation         sql.NullString
	Education          sql.NullString
	Address            sql.NullString
	PhoneHome          sql.NullString
	PhoneWork          sql.NullString
	PhoneMobile        sql.NullString
	Faxno              sql.NullString
	Email              sql.NullString
	Username           sql.NullString
	Password           sql.NullString
	Readonly           sql.NullInt32
	Warnings           sql.NullInt32
	AllowToSave        sql.NullInt32
	AllowToCloud       sql.NullInt32
	Flag2              sql.NullInt32
	Idsport            sql.NullInt32
	Medication         sql.NullString
	Addinfo            sql.NullString
	TeamName           sql.NullString
	Add1               sql.NullInt32
	Athlete            sql.NullInt32
	Add10              sql.NullString
	Add20              sql.NullString
	Updatemode         sql.NullInt32
	WeightKg           sql.NullFloat64
	HeightCm           sql.NullFloat64
	DateModified       sql.NullFloat64
	RecomTestlevel     sql.NullInt32
	CreatedBy          sql.NullInt64
	ModBy              sql.NullInt64
	ModDate            sql.NullTime
	Deleted            sql.NullInt16
	CreatedDate        sql.NullTime
	Modded             sql.NullInt16
	AllowAnonymousData sql.NullBool
	Locked             sql.NullInt16
	AllowToSprintai    sql.NullInt32
	TosprintaiFrom     sql.NullTime
	StatSent           sql.NullTime
	SporttiID          sql.NullString
}

// Prefer updating customer metadata if it already exists.
func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) error {
	_, err := q.exec(ctx, q.upsertCustomerStmt, upsertCustomer,
		arg.Idcustomer,
		arg.Firstname,
		arg.Lastname,
		arg.Idgroups,
		arg.Dob,
		arg.Sex,
		arg.DobYear,
		arg.DobMonth,
		arg.DobDay,
		arg.PidNumber,
		arg.Company,
		arg.Occupation,
		arg.Education,
		arg.Address,
		arg.PhoneHome,
		arg.PhoneWork,
		arg.PhoneMobile,
		arg.Faxno,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Readonly,
		arg.Warnings,
		arg.AllowToSave,
		arg.AllowToCloud,
		arg.Flag2,
		arg.Idsport,
		arg.Medication,
		arg.Addinfo,
		arg.TeamName,
		arg.Add1,
		arg.Athlete,
		arg.Add10,
		arg.Add20,
		arg.Updatemode,
		arg.WeightKg,
		arg.HeightCm,
		arg.DateModified,
		arg.RecomTestlevel,
		arg.CreatedBy,
		arg.ModBy,
		arg.ModDate,
		arg.Deleted,
		arg.CreatedDate,
		arg.Modded,
		arg.AllowAnonymousData,
		arg.Locked,
		arg.AllowToSprintai,
		arg.TosprintaiFrom,
		arg.StatSent,
		arg.SporttiID,
	)
	return err
}
