// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package fissqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getAthleteResultsJPStmt, err = db.PrepareContext(ctx, getAthleteResultsJP); err != nil {
		return nil, fmt.Errorf("error preparing query GetAthleteResultsJP: %w", err)
	}
	if q.getAthleteResultsNKStmt, err = db.PrepareContext(ctx, getAthleteResultsNK); err != nil {
		return nil, fmt.Errorf("error preparing query GetAthleteResultsNK: %w", err)
	}
	if q.getAthletesBySectorStmt, err = db.PrepareContext(ctx, getAthletesBySector); err != nil {
		return nil, fmt.Errorf("error preparing query GetAthletesBySector: %w", err)
	}
	if q.getCompetitorIDByFiscodeJPStmt, err = db.PrepareContext(ctx, getCompetitorIDByFiscodeJP); err != nil {
		return nil, fmt.Errorf("error preparing query GetCompetitorIDByFiscodeJP: %w", err)
	}
	if q.getCompetitorIDByFiscodeNKStmt, err = db.PrepareContext(ctx, getCompetitorIDByFiscodeNK); err != nil {
		return nil, fmt.Errorf("error preparing query GetCompetitorIDByFiscodeNK: %w", err)
	}
	if q.getCompetitorIDsByGenderAndNationJPStmt, err = db.PrepareContext(ctx, getCompetitorIDsByGenderAndNationJP); err != nil {
		return nil, fmt.Errorf("error preparing query GetCompetitorIDsByGenderAndNationJP: %w", err)
	}
	if q.getNationsBySectorStmt, err = db.PrepareContext(ctx, getNationsBySector); err != nil {
		return nil, fmt.Errorf("error preparing query GetNationsBySector: %w", err)
	}
	if q.getNordicCombinedCategoriesStmt, err = db.PrepareContext(ctx, getNordicCombinedCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetNordicCombinedCategories: %w", err)
	}
	if q.getNordicCombinedDisciplinesStmt, err = db.PrepareContext(ctx, getNordicCombinedDisciplines); err != nil {
		return nil, fmt.Errorf("error preparing query GetNordicCombinedDisciplines: %w", err)
	}
	if q.getNordicCombinedSeasonsStmt, err = db.PrepareContext(ctx, getNordicCombinedSeasons); err != nil {
		return nil, fmt.Errorf("error preparing query GetNordicCombinedSeasons: %w", err)
	}
	if q.getRaceResultsJPByRaceIDStmt, err = db.PrepareContext(ctx, getRaceResultsJPByRaceID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRaceResultsJPByRaceID: %w", err)
	}
	if q.getRaceResultsNKByRaceIDStmt, err = db.PrepareContext(ctx, getRaceResultsNKByRaceID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRaceResultsNKByRaceID: %w", err)
	}
	if q.getResultsByCompetitorsJPStmt, err = db.PrepareContext(ctx, getResultsByCompetitorsJP); err != nil {
		return nil, fmt.Errorf("error preparing query GetResultsByCompetitorsJP: %w", err)
	}
	if q.getSkiJumpingCategoriesStmt, err = db.PrepareContext(ctx, getSkiJumpingCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetSkiJumpingCategories: %w", err)
	}
	if q.getSkiJumpingDisciplinesStmt, err = db.PrepareContext(ctx, getSkiJumpingDisciplines); err != nil {
		return nil, fmt.Errorf("error preparing query GetSkiJumpingDisciplines: %w", err)
	}
	if q.getSkiJumpingSeasonsStmt, err = db.PrepareContext(ctx, getSkiJumpingSeasons); err != nil {
		return nil, fmt.Errorf("error preparing query GetSkiJumpingSeasons: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getAthleteResultsJPStmt != nil {
		if cerr := q.getAthleteResultsJPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAthleteResultsJPStmt: %w", cerr)
		}
	}
	if q.getAthleteResultsNKStmt != nil {
		if cerr := q.getAthleteResultsNKStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAthleteResultsNKStmt: %w", cerr)
		}
	}
	if q.getAthletesBySectorStmt != nil {
		if cerr := q.getAthletesBySectorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAthletesBySectorStmt: %w", cerr)
		}
	}
	if q.getCompetitorIDByFiscodeJPStmt != nil {
		if cerr := q.getCompetitorIDByFiscodeJPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCompetitorIDByFiscodeJPStmt: %w", cerr)
		}
	}
	if q.getCompetitorIDByFiscodeNKStmt != nil {
		if cerr := q.getCompetitorIDByFiscodeNKStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCompetitorIDByFiscodeNKStmt: %w", cerr)
		}
	}
	if q.getCompetitorIDsByGenderAndNationJPStmt != nil {
		if cerr := q.getCompetitorIDsByGenderAndNationJPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCompetitorIDsByGenderAndNationJPStmt: %w", cerr)
		}
	}
	if q.getNationsBySectorStmt != nil {
		if cerr := q.getNationsBySectorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNationsBySectorStmt: %w", cerr)
		}
	}
	if q.getNordicCombinedCategoriesStmt != nil {
		if cerr := q.getNordicCombinedCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNordicCombinedCategoriesStmt: %w", cerr)
		}
	}
	if q.getNordicCombinedDisciplinesStmt != nil {
		if cerr := q.getNordicCombinedDisciplinesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNordicCombinedDisciplinesStmt: %w", cerr)
		}
	}
	if q.getNordicCombinedSeasonsStmt != nil {
		if cerr := q.getNordicCombinedSeasonsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNordicCombinedSeasonsStmt: %w", cerr)
		}
	}
	if q.getRaceResultsJPByRaceIDStmt != nil {
		if cerr := q.getRaceResultsJPByRaceIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRaceResultsJPByRaceIDStmt: %w", cerr)
		}
	}
	if q.getRaceResultsNKByRaceIDStmt != nil {
		if cerr := q.getRaceResultsNKByRaceIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRaceResultsNKByRaceIDStmt: %w", cerr)
		}
	}
	if q.getResultsByCompetitorsJPStmt != nil {
		if cerr := q.getResultsByCompetitorsJPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getResultsByCompetitorsJPStmt: %w", cerr)
		}
	}
	if q.getSkiJumpingCategoriesStmt != nil {
		if cerr := q.getSkiJumpingCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSkiJumpingCategoriesStmt: %w", cerr)
		}
	}
	if q.getSkiJumpingDisciplinesStmt != nil {
		if cerr := q.getSkiJumpingDisciplinesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSkiJumpingDisciplinesStmt: %w", cerr)
		}
	}
	if q.getSkiJumpingSeasonsStmt != nil {
		if cerr := q.getSkiJumpingSeasonsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSkiJumpingSeasonsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                      DBTX
	tx                                      *sql.Tx
	getAthleteResultsJPStmt                 *sql.Stmt
	getAthleteResultsNKStmt                 *sql.Stmt
	getAthletesBySectorStmt                 *sql.Stmt
	getCompetitorIDByFiscodeJPStmt          *sql.Stmt
	getCompetitorIDByFiscodeNKStmt          *sql.Stmt
	getCompetitorIDsByGenderAndNationJPStmt *sql.Stmt
	getNationsBySectorStmt                  *sql.Stmt
	getNordicCombinedCategoriesStmt         *sql.Stmt
	getNordicCombinedDisciplinesStmt        *sql.Stmt
	getNordicCombinedSeasonsStmt            *sql.Stmt
	getRaceResultsJPByRaceIDStmt            *sql.Stmt
	getRaceResultsNKByRaceIDStmt            *sql.Stmt
	getResultsByCompetitorsJPStmt           *sql.Stmt
	getSkiJumpingCategoriesStmt             *sql.Stmt
	getSkiJumpingDisciplinesStmt            *sql.Stmt
	getSkiJumpingSeasonsStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		getAthleteResultsJPStmt:                 q.getAthleteResultsJPStmt,
		getAthleteResultsNKStmt:                 q.getAthleteResultsNKStmt,
		getAthletesBySectorStmt:                 q.getAthletesBySectorStmt,
		getCompetitorIDByFiscodeJPStmt:          q.getCompetitorIDByFiscodeJPStmt,
		getCompetitorIDByFiscodeNKStmt:          q.getCompetitorIDByFiscodeNKStmt,
		getCompetitorIDsByGenderAndNationJPStmt: q.getCompetitorIDsByGenderAndNationJPStmt,
		getNationsBySectorStmt:                  q.getNationsBySectorStmt,
		getNordicCombinedCategoriesStmt:         q.getNordicCombinedCategoriesStmt,
		getNordicCombinedDisciplinesStmt:        q.getNordicCombinedDisciplinesStmt,
		getNordicCombinedSeasonsStmt:            q.getNordicCombinedSeasonsStmt,
		getRaceResultsJPByRaceIDStmt:            q.getRaceResultsJPByRaceIDStmt,
		getRaceResultsNKByRaceIDStmt:            q.getRaceResultsNKByRaceIDStmt,
		getResultsByCompetitorsJPStmt:           q.getResultsByCompetitorsJPStmt,
		getSkiJumpingCategoriesStmt:             q.getSkiJumpingCategoriesStmt,
		getSkiJumpingDisciplinesStmt:            q.getSkiJumpingDisciplinesStmt,
		getSkiJumpingSeasonsStmt:                q.getSkiJumpingSeasonsStmt,
	}
}
