// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package fissqlc

import (
	"context"
	"database/sql"
)

const getAthleteResultsJP = `-- name: GetAthleteResultsJP :many
SELECT 
    A_resultJP.RaceID,
    A_resultJP.Position,
    A_raceJP.RaceDate,
    A_raceJP.SeasonCode,
    A_raceJP.DisciplineCode,
    A_raceJP.CatCode,
    A_raceJP.Place,
    A_resultJP.PosR1,
    A_resultJP.SpeedR1,
    A_resultJP.DistR1,
    A_resultJP.JudPtsR1,
    A_resultJP.WindR1,
    A_resultJP.WindPtsR1,
    A_resultJP.GateR1,
    A_resultJP.PosR2,
    A_resultJP.SpeedR2,
    A_resultJP.DistR2,
    A_resultJP.JudPtsR2,
    A_resultJP.WindR2,
    A_resultJP.WindPtsR2,
    A_resultJP.GateR2
FROM A_resultJP
INNER JOIN A_raceJP ON A_resultJP.RaceID = A_raceJP.RaceID
WHERE A_resultJP.CompetitorID = $1
  AND (A_raceJP.SeasonCode = ANY($2) OR $2 IS NULL)
  AND (A_raceJP.DisciplineCode = ANY($3) OR $3 IS NULL)
  AND (A_raceJP.CatCode = ANY($4) OR $4 IS NULL)
ORDER BY A_raceJP.RaceDate
`

type GetAthleteResultsJPParams struct {
	Competitorid   sql.NullInt32
	Seasoncode     sql.NullInt32
	Disciplinecode sql.NullString
	Catcode        sql.NullString
}

type GetAthleteResultsJPRow struct {
	Raceid         sql.NullInt32
	Position       sql.NullInt32
	Racedate       sql.NullTime
	Seasoncode     sql.NullInt32
	Disciplinecode sql.NullString
	Catcode        sql.NullString
	Place          sql.NullString
	Posr1          sql.NullString
	Speedr1        sql.NullString
	Distr1         sql.NullString
	Judptsr1       sql.NullString
	Windr1         sql.NullString
	Windptsr1      sql.NullString
	Gater1         sql.NullString
	Posr2          sql.NullString
	Speedr2        sql.NullString
	Distr2         sql.NullString
	Judptsr2       sql.NullString
	Windr2         sql.NullString
	Windptsr2      sql.NullString
	Gater2         sql.NullString
}

func (q *Queries) GetAthleteResultsJP(ctx context.Context, arg GetAthleteResultsJPParams) ([]GetAthleteResultsJPRow, error) {
	rows, err := q.query(ctx, q.getAthleteResultsJPStmt, getAthleteResultsJP,
		arg.Competitorid,
		arg.Seasoncode,
		arg.Disciplinecode,
		arg.Catcode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAthleteResultsJPRow
	for rows.Next() {
		var i GetAthleteResultsJPRow
		if err := rows.Scan(
			&i.Raceid,
			&i.Position,
			&i.Racedate,
			&i.Seasoncode,
			&i.Disciplinecode,
			&i.Catcode,
			&i.Place,
			&i.Posr1,
			&i.Speedr1,
			&i.Distr1,
			&i.Judptsr1,
			&i.Windr1,
			&i.Windptsr1,
			&i.Gater1,
			&i.Posr2,
			&i.Speedr2,
			&i.Distr2,
			&i.Judptsr2,
			&i.Windr2,
			&i.Windptsr2,
			&i.Gater2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteResultsNK = `-- name: GetAthleteResultsNK :many
SELECT 
    A_resultNK.RecID,
    A_resultNK.RaceID,
    A_resultNK.Position,
    A_raceNK.RaceDate,
    A_raceNK.SeasonCode,
    A_raceNK.Distance,
    A_raceNK.Hill,
    A_raceNK.DisciplineCode,
    A_raceNK.CatCode,
    A_raceNK.Place,
    A_resultNK.PosR1,
    A_resultNK.SpeedR1,
    A_resultNK.DistR1,
    A_resultNK.JudPtsR1,
    A_resultNK.WindR1,
    A_resultNK.WindPtsR1,
    A_resultNK.GateR1,
    A_resultNK.TotRun1,
    A_resultNK.PosCC,
    A_resultNK.TimeTot,
    A_resultNK.TimeTotInt,
    A_resultNK.PointsJump
FROM A_resultNK
INNER JOIN A_raceNK ON A_resultNK.RaceID = A_raceNK.RaceID
WHERE A_resultNK.CompetitorID = $1
  AND (A_raceNK.SeasonCode = ANY($2) OR $2 IS NULL)
  AND (A_raceNK.DisciplineCode = ANY($3) OR $3 IS NULL)
  AND (A_raceNK.CatCode = ANY($4) OR $4 IS NULL)
ORDER BY A_raceNK.RaceDate
`

type GetAthleteResultsNKParams struct {
	Competitorid   sql.NullInt32
	Seasoncode     sql.NullInt32
	Disciplinecode sql.NullString
	Catcode        sql.NullString
}

type GetAthleteResultsNKRow struct {
	Recid          sql.NullInt32
	Raceid         sql.NullInt32
	Position       sql.NullInt32
	Racedate       sql.NullTime
	Seasoncode     sql.NullInt32
	Distance       sql.NullString
	Hill           sql.NullInt32
	Disciplinecode sql.NullString
	Catcode        sql.NullString
	Place          sql.NullString
	Posr1          sql.NullString
	Speedr1        sql.NullString
	Distr1         sql.NullString
	Judptsr1       sql.NullString
	Windr1         sql.NullString
	Windptsr1      sql.NullString
	Gater1         sql.NullString
	Totrun1        sql.NullString
	Poscc          sql.NullString
	Timetot        sql.NullString
	Timetotint     sql.NullInt32
	Pointsjump     sql.NullString
}

func (q *Queries) GetAthleteResultsNK(ctx context.Context, arg GetAthleteResultsNKParams) ([]GetAthleteResultsNKRow, error) {
	rows, err := q.query(ctx, q.getAthleteResultsNKStmt, getAthleteResultsNK,
		arg.Competitorid,
		arg.Seasoncode,
		arg.Disciplinecode,
		arg.Catcode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAthleteResultsNKRow
	for rows.Next() {
		var i GetAthleteResultsNKRow
		if err := rows.Scan(
			&i.Recid,
			&i.Raceid,
			&i.Position,
			&i.Racedate,
			&i.Seasoncode,
			&i.Distance,
			&i.Hill,
			&i.Disciplinecode,
			&i.Catcode,
			&i.Place,
			&i.Posr1,
			&i.Speedr1,
			&i.Distr1,
			&i.Judptsr1,
			&i.Windr1,
			&i.Windptsr1,
			&i.Gater1,
			&i.Totrun1,
			&i.Poscc,
			&i.Timetot,
			&i.Timetotint,
			&i.Pointsjump,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthletesBySector = `-- name: GetAthletesBySector :many
SELECT Firstname, Lastname, Fiscode
FROM A_competitor
WHERE SectorCode = $1
ORDER BY Fiscode
`

type GetAthletesBySectorRow struct {
	Firstname sql.NullString
	Lastname  sql.NullString
	Fiscode   sql.NullInt32
}

func (q *Queries) GetAthletesBySector(ctx context.Context, sectorcode sql.NullString) ([]GetAthletesBySectorRow, error) {
	rows, err := q.query(ctx, q.getAthletesBySectorStmt, getAthletesBySector, sectorcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAthletesBySectorRow
	for rows.Next() {
		var i GetAthletesBySectorRow
		if err := rows.Scan(&i.Firstname, &i.Lastname, &i.Fiscode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompetitorIDByFiscodeJP = `-- name: GetCompetitorIDByFiscodeJP :one
SELECT CompetitorID
FROM A_competitor
WHERE Fiscode = $1 AND SectorCode = 'JP'
`

func (q *Queries) GetCompetitorIDByFiscodeJP(ctx context.Context, fiscode sql.NullInt32) (sql.NullInt32, error) {
	row := q.queryRow(ctx, q.getCompetitorIDByFiscodeJPStmt, getCompetitorIDByFiscodeJP, fiscode)
	var competitorid sql.NullInt32
	err := row.Scan(&competitorid)
	return competitorid, err
}

const getCompetitorIDByFiscodeNK = `-- name: GetCompetitorIDByFiscodeNK :one
SELECT CompetitorID
FROM A_competitor
WHERE Fiscode = $1 AND SectorCode = 'NK'
`

func (q *Queries) GetCompetitorIDByFiscodeNK(ctx context.Context, fiscode sql.NullInt32) (sql.NullInt32, error) {
	row := q.queryRow(ctx, q.getCompetitorIDByFiscodeNKStmt, getCompetitorIDByFiscodeNK, fiscode)
	var competitorid sql.NullInt32
	err := row.Scan(&competitorid)
	return competitorid, err
}

const getCompetitorIDsByGenderAndNationJP = `-- name: GetCompetitorIDsByGenderAndNationJP :many
SELECT CompetitorID
FROM A_competitor
WHERE Gender = $1 AND NationCode = $2 AND SectorCode = 'JP'
`

type GetCompetitorIDsByGenderAndNationJPParams struct {
	Gender     sql.NullString
	Nationcode sql.NullString
}

func (q *Queries) GetCompetitorIDsByGenderAndNationJP(ctx context.Context, arg GetCompetitorIDsByGenderAndNationJPParams) ([]sql.NullInt32, error) {
	rows, err := q.query(ctx, q.getCompetitorIDsByGenderAndNationJPStmt, getCompetitorIDsByGenderAndNationJP, arg.Gender, arg.Nationcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt32
	for rows.Next() {
		var competitorid sql.NullInt32
		if err := rows.Scan(&competitorid); err != nil {
			return nil, err
		}
		items = append(items, competitorid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNationsBySector = `-- name: GetNationsBySector :many
SELECT DISTINCT NationCode
FROM A_competitor
WHERE SectorCode = $1
ORDER BY NationCode ASC
`

func (q *Queries) GetNationsBySector(ctx context.Context, sectorcode sql.NullString) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.getNationsBySectorStmt, getNationsBySector, sectorcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var nationcode sql.NullString
		if err := rows.Scan(&nationcode); err != nil {
			return nil, err
		}
		items = append(items, nationcode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNordicCombinedCategories = `-- name: GetNordicCombinedCategories :many
SELECT DISTINCT CatCode
FROM A_raceNK
ORDER BY CatCode ASC
`

func (q *Queries) GetNordicCombinedCategories(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.getNordicCombinedCategoriesStmt, getNordicCombinedCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var catcode sql.NullString
		if err := rows.Scan(&catcode); err != nil {
			return nil, err
		}
		items = append(items, catcode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNordicCombinedDisciplines = `-- name: GetNordicCombinedDisciplines :many
SELECT DISTINCT DisciplineCode
FROM A_raceNK
ORDER BY DisciplineCode ASC
`

func (q *Queries) GetNordicCombinedDisciplines(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.getNordicCombinedDisciplinesStmt, getNordicCombinedDisciplines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var disciplinecode sql.NullString
		if err := rows.Scan(&disciplinecode); err != nil {
			return nil, err
		}
		items = append(items, disciplinecode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNordicCombinedSeasons = `-- name: GetNordicCombinedSeasons :many
SELECT DISTINCT SeasonCode
FROM A_raceNK
ORDER BY SeasonCode DESC
`

func (q *Queries) GetNordicCombinedSeasons(ctx context.Context) ([]sql.NullInt32, error) {
	rows, err := q.query(ctx, q.getNordicCombinedSeasonsStmt, getNordicCombinedSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt32
	for rows.Next() {
		var seasoncode sql.NullInt32
		if err := rows.Scan(&seasoncode); err != nil {
			return nil, err
		}
		items = append(items, seasoncode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRaceResultsJPByRaceID = `-- name: GetRaceResultsJPByRaceID :many
SELECT 
    RecID,
    RaceID,
    Position,
    SpeedR1,
    DistR1,
    JudptsR1,
    PosR1,
    GateR1,
    SpeedR2,
    DistR2,
    JudptsR2,
    PosR2,
    GateR2
FROM A_resultjp
WHERE (RaceID = ANY($1))
ORDER BY RaceID
`

type GetRaceResultsJPByRaceIDRow struct {
	Recid    sql.NullInt32
	Raceid   sql.NullInt32
	Position sql.NullInt32
	Speedr1  sql.NullString
	Distr1   sql.NullString
	Judptsr1 sql.NullString
	Posr1    sql.NullString
	Gater1   sql.NullString
	Speedr2  sql.NullString
	Distr2   sql.NullString
	Judptsr2 sql.NullString
	Posr2    sql.NullString
	Gater2   sql.NullString
}

func (q *Queries) GetRaceResultsJPByRaceID(ctx context.Context, raceid sql.NullInt32) ([]GetRaceResultsJPByRaceIDRow, error) {
	rows, err := q.query(ctx, q.getRaceResultsJPByRaceIDStmt, getRaceResultsJPByRaceID, raceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRaceResultsJPByRaceIDRow
	for rows.Next() {
		var i GetRaceResultsJPByRaceIDRow
		if err := rows.Scan(
			&i.Recid,
			&i.Raceid,
			&i.Position,
			&i.Speedr1,
			&i.Distr1,
			&i.Judptsr1,
			&i.Posr1,
			&i.Gater1,
			&i.Speedr2,
			&i.Distr2,
			&i.Judptsr2,
			&i.Posr2,
			&i.Gater2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRaceResultsNKByRaceID = `-- name: GetRaceResultsNKByRaceID :many
SELECT 
    RecID,
    RaceID,
    Position,
    SpeedR1,
    DistR1,
    JudptsR1,
    PosR1,
    GateR1,
    TotRun1,
    Pointsjump,
    Poscc,
    Timetot,
    Timetotint
FROM A_resultnk
WHERE (RaceID = ANY($1))
ORDER BY RaceID
`

type GetRaceResultsNKByRaceIDRow struct {
	Recid      sql.NullInt32
	Raceid     sql.NullInt32
	Position   sql.NullInt32
	Speedr1    sql.NullString
	Distr1     sql.NullString
	Judptsr1   sql.NullString
	Posr1      sql.NullString
	Gater1     sql.NullString
	Totrun1    sql.NullString
	Pointsjump sql.NullString
	Poscc      sql.NullString
	Timetot    sql.NullString
	Timetotint sql.NullInt32
}

func (q *Queries) GetRaceResultsNKByRaceID(ctx context.Context, raceid sql.NullInt32) ([]GetRaceResultsNKByRaceIDRow, error) {
	rows, err := q.query(ctx, q.getRaceResultsNKByRaceIDStmt, getRaceResultsNKByRaceID, raceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRaceResultsNKByRaceIDRow
	for rows.Next() {
		var i GetRaceResultsNKByRaceIDRow
		if err := rows.Scan(
			&i.Recid,
			&i.Raceid,
			&i.Position,
			&i.Speedr1,
			&i.Distr1,
			&i.Judptsr1,
			&i.Posr1,
			&i.Gater1,
			&i.Totrun1,
			&i.Pointsjump,
			&i.Poscc,
			&i.Timetot,
			&i.Timetotint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultsByCompetitorsJP = `-- name: GetResultsByCompetitorsJP :many
SELECT 
    A_resultJP.RaceID,
    A_resultJP.Position,
    A_raceJP.RaceDate,
    A_raceJP.SeasonCode,
    A_raceJP.DisciplineCode,
    A_raceJP.CatCode,
    A_raceJP.Place,
    A_resultJP.PosR1,
    A_resultJP.SpeedR1,
    A_resultJP.DistR1,
    A_resultJP.JudPtsR1,
    A_resultJP.WindR1,
    A_resultJP.WindPtsR1,
    A_resultJP.GateR1,
    A_resultJP.PosR2,
    A_resultJP.SpeedR2,
    A_resultJP.DistR2,
    A_resultJP.JudPtsR2,
    A_resultJP.WindR2,
    A_resultJP.WindPtsR2,
    A_resultJP.GateR2
FROM A_resultJP
INNER JOIN A_raceJP ON A_resultJP.RaceID = A_raceJP.RaceID
WHERE A_resultJP.CompetitorID = ANY($1)
  AND (A_raceJP.SeasonCode = ANY($2) OR $2 IS NULL)
  AND (A_raceJP.DisciplineCode = ANY($3) OR $3 IS NULL)
  AND (A_raceJP.CatCode = ANY($4) OR $4 IS NULL)
ORDER BY A_raceJP.RaceDate
`

type GetResultsByCompetitorsJPParams struct {
	Competitorid   sql.NullInt32
	Seasoncode     sql.NullInt32
	Disciplinecode sql.NullString
	Catcode        sql.NullString
}

type GetResultsByCompetitorsJPRow struct {
	Raceid         sql.NullInt32
	Position       sql.NullInt32
	Racedate       sql.NullTime
	Seasoncode     sql.NullInt32
	Disciplinecode sql.NullString
	Catcode        sql.NullString
	Place          sql.NullString
	Posr1          sql.NullString
	Speedr1        sql.NullString
	Distr1         sql.NullString
	Judptsr1       sql.NullString
	Windr1         sql.NullString
	Windptsr1      sql.NullString
	Gater1         sql.NullString
	Posr2          sql.NullString
	Speedr2        sql.NullString
	Distr2         sql.NullString
	Judptsr2       sql.NullString
	Windr2         sql.NullString
	Windptsr2      sql.NullString
	Gater2         sql.NullString
}

func (q *Queries) GetResultsByCompetitorsJP(ctx context.Context, arg GetResultsByCompetitorsJPParams) ([]GetResultsByCompetitorsJPRow, error) {
	rows, err := q.query(ctx, q.getResultsByCompetitorsJPStmt, getResultsByCompetitorsJP,
		arg.Competitorid,
		arg.Seasoncode,
		arg.Disciplinecode,
		arg.Catcode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsByCompetitorsJPRow
	for rows.Next() {
		var i GetResultsByCompetitorsJPRow
		if err := rows.Scan(
			&i.Raceid,
			&i.Position,
			&i.Racedate,
			&i.Seasoncode,
			&i.Disciplinecode,
			&i.Catcode,
			&i.Place,
			&i.Posr1,
			&i.Speedr1,
			&i.Distr1,
			&i.Judptsr1,
			&i.Windr1,
			&i.Windptsr1,
			&i.Gater1,
			&i.Posr2,
			&i.Speedr2,
			&i.Distr2,
			&i.Judptsr2,
			&i.Windr2,
			&i.Windptsr2,
			&i.Gater2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkiJumpingCategories = `-- name: GetSkiJumpingCategories :many
SELECT DISTINCT CatCode
FROM A_raceJP
ORDER BY CatCode ASC
`

func (q *Queries) GetSkiJumpingCategories(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.getSkiJumpingCategoriesStmt, getSkiJumpingCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var catcode sql.NullString
		if err := rows.Scan(&catcode); err != nil {
			return nil, err
		}
		items = append(items, catcode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkiJumpingDisciplines = `-- name: GetSkiJumpingDisciplines :many
SELECT DISTINCT DisciplineCode
FROM A_raceJP
ORDER BY DisciplineCode ASC
`

func (q *Queries) GetSkiJumpingDisciplines(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.getSkiJumpingDisciplinesStmt, getSkiJumpingDisciplines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var disciplinecode sql.NullString
		if err := rows.Scan(&disciplinecode); err != nil {
			return nil, err
		}
		items = append(items, disciplinecode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkiJumpingSeasons = `-- name: GetSkiJumpingSeasons :many
SELECT DISTINCT SeasonCode
FROM A_raceJP
ORDER BY SeasonCode DESC
`

func (q *Queries) GetSkiJumpingSeasons(ctx context.Context) ([]sql.NullInt32, error) {
	rows, err := q.query(ctx, q.getSkiJumpingSeasonsStmt, getSkiJumpingSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt32
	for rows.Next() {
		var seasoncode sql.NullInt32
		if err := rows.Scan(&seasoncode); err != nil {
			return nil, err
		}
		items = append(items, seasoncode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
