--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg110+1)
-- Dumped by pg_dump version 18.0 (Ubuntu 18.0-1.pgdg24.04+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: injuries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.injuries (
    user_id integer DEFAULT 0 NOT NULL,
    injury_type integer DEFAULT 0 NOT NULL,
    severity integer DEFAULT 0 NOT NULL,
    pain_level integer DEFAULT 0 NOT NULL,
    description character varying(255) NOT NULL,
    date_start timestamp without time zone DEFAULT now() NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    date_end timestamp without time zone,
    injury_id integer DEFAULT 0 NOT NULL,
    meta character varying(255) NOT NULL
);


--
-- Name: querys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.querys (
    user_id integer DEFAULT 0 NOT NULL,
    query_type integer DEFAULT 0 NOT NULL,
    answers character varying(255) NOT NULL,
    comment character varying(255) NOT NULL,
    "timestamp" timestamp without time zone DEFAULT now() NOT NULL,
    meta character varying(255) NOT NULL,
    id bigint NOT NULL
);


--
-- Name: querys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.querys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.querys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    username integer,
    role_id integer,
    password character varying(255),
    email character varying(255),
    share_permission integer,
    collect_permission integer,
    eula_accepted integer,
    create_time timestamp without time zone,
    message character varying(255),
    salt character varying(255)
);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT ALL ON SCHEMA public TO kamkadmin;


--
-- PostgreSQL database dump complete
--
