// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://csc.fi/en/security-privacy-data-policy-and-open-source-policy/privacy/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Healthcheck endpoint",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ops"
                ],
                "summary": "Healthcheck",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/utv/oura/data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns data for the specified user on the specified date (optionally filtered by key)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available data (Oura)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data",
                        "schema": {
                            "$ref": "#/definitions/swagger.OuraDataResponse"
                        }
                    },
                    "204": {
                        "description": "No Content: No data found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/utv/oura/dates": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns available dates for the specified user (optionally filtered by date range)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available dates (Oura)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter dates after this date (YYYY-MM-DD)",
                        "name": "after_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter dates before this date (YYYY-MM-DD)",
                        "name": "before_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available dates",
                        "schema": {
                            "$ref": "#/definitions/swagger.OuraDatesResponse"
                        }
                    },
                    "204": {
                        "description": "No Content: No available dates found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ValidationErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/swagger.OuraInvalidDateRange"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/utv/oura/types": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns available types for the specified user on the specified date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available types (Oura)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available types",
                        "schema": {
                            "$ref": "#/definitions/swagger.OuraTypesResponse"
                        }
                    },
                    "204": {
                        "description": "No Content: No available types found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/utv/polar/data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns data for the specified user on the specified date (optionally filtered by key)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available data (Polar)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "204": {
                        "description": "No Content: No data found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/utv/polar/dates": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns available dates for the specified user (optionally filtered by date range)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available dates (Polar)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter dates after this date (YYYY-MM-DD)",
                        "name": "after_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter dates before this date (YYYY-MM-DD)",
                        "name": "before_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available dates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content: No available dates found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/utv/polar/types": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns available types for the specified user on the specified date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available types (Polar)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available types",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content: No available types found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/utv/suunto/data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns data for the specified user on the specified date (optionally filtered by key)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available data (Suunto)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "204": {
                        "description": "No Content: No data found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/utv/suunto/dates": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns available dates for the specified user (optionally filtered by date range)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available dates (Suunto)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter dates after this date (YYYY-MM-DD)",
                        "name": "after_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter dates before this date (YYYY-MM-DD)",
                        "name": "before_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available dates",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content: No available dates found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/utv/suunto/types": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns available types for the specified user on the specified date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTV"
                ],
                "summary": "Get available types (Suunto)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available types",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content: No available types found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "swagger.DailyActivity": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string",
                    "example": "2023-12-01"
                },
                "sedentary_time": {
                    "type": "integer",
                    "example": 27480
                },
                "steps": {
                    "type": "integer",
                    "example": 6653
                },
                "total_calories": {
                    "type": "integer",
                    "example": 4272
                }
            }
        },
        "swagger.HeartRateData": {
            "type": "object",
            "properties": {
                "bpm": {
                    "type": "integer",
                    "example": 43
                },
                "source": {
                    "type": "string",
                    "example": "rest"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-12-01T00:00:43+00:00"
                }
            }
        },
        "swagger.InternalServerError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "the server encountered a problem"
                }
            }
        },
        "swagger.InternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.InternalServerError"
                    }
                }
            }
        },
        "swagger.OuraData": {
            "type": "object",
            "properties": {
                "daily_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.DailyActivity"
                    }
                },
                "heartrate": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.HeartRateData"
                    }
                },
                "sleep": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.SleepData"
                    }
                }
            }
        },
        "swagger.OuraDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger.OuraData"
                }
            }
        },
        "swagger.OuraDatesResponse": {
            "type": "object",
            "properties": {
                "dates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2024-02-25",
                        "2024-02-26",
                        "2024-03-25"
                    ]
                }
            }
        },
        "swagger.OuraInvalidDateRange": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.UnprocessableEntityError"
                    }
                }
            }
        },
        "swagger.OuraTypesResponse": {
            "type": "object",
            "properties": {
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "heartrate",
                        "sleep",
                        "daily_activity"
                    ]
                }
            }
        },
        "swagger.SleepData": {
            "type": "object",
            "properties": {
                "average_heart_rate": {
                    "type": "integer",
                    "example": 47
                },
                "awake_time": {
                    "type": "integer",
                    "example": 1530
                },
                "bedtime_end": {
                    "type": "string",
                    "example": "2023-12-01T06:21:59+02:00"
                },
                "bedtime_start": {
                    "type": "string",
                    "example": "2023-11-30T23:23:59+02:00"
                },
                "day": {
                    "type": "string",
                    "example": "2023-12-01"
                },
                "deep_sleep_duration": {
                    "type": "integer",
                    "example": 6630
                },
                "id": {
                    "type": "string",
                    "example": "82496435-af96-462e-90c9-806d38418e87"
                },
                "type": {
                    "type": "string",
                    "example": "long_sleep"
                }
            }
        },
        "swagger.UnprocessableEntityError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid date range"
                }
            }
        },
        "swagger.ValidationError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "full description of the error"
                }
            }
        },
        "swagger.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.ValidationError"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "KUHA REST API",
	Description:      "API for integrating, analyzing, and visualizing sports and health data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
